"""Tutor loop v1 (build plan Part 7, architecture section 7) — fully local.

Wires the runtime described in architecture section 19:

    student text
    -> CognitiveAnalyzer (Part 1 classifier + Part 2 resolver, MiniLM, local)
    -> learner state update (EMA globals + flags)
    -> rule-based pedagogy decision (v1 rules below) + PolicyShadow suggestion (logged)
    -> evidence retrieval reusing query.py's machinery (bridge gate, misconception
       probe-first mechanics, need evidence, 7-term snapshot rerank, cohesion check)
       over a LOCAL MiniLM chunk index (the Gemini FAISS index is not touched)
    -> response generated by the LOCAL Qwen model (llama.cpp server, GPU)
       composed ONLY from manifest items
    -> learning_log.jsonl append + state save

No cloud calls anywhere: embeddings are MiniLM, generation is Qwen. Start the
llama server first:
    python F:/Projects/Pedagogical_study_pkg/scripts/run_llama_server.py

Usage:
    python tutor_loop.py                      # interactive chat
    python tutor_loop.py --once "message"     # single scripted turn (for tests)
    python tutor_loop.py --once "..." --no-answer   # skip Qwen generation
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import requests

from cognitive_analyzer import CognitiveAnalyzer
from hope_detector import HopeDetector
from learner_state import load_learner_state
from policy_shadow import PolicyShadow
from query import (
    Snapshot,
    bridge_evidence,
    cohesion_filter,
    ev,
    load_store,
    misconception_evidence,
    need_evidence,
    resolve_band,
    snapshot_rerank,
)

ROOT = Path(__file__).resolve().parent
STORE = ROOT / "rag_store"
CHUNK_INDEX_DIR = ROOT / "models" / "local_chunk_index"
QWEN = "http://127.0.0.1:8080"

# ---------------------------------------------------------------------------
# Rule-based pedagogy decision v1 (architecture section 6.6 / section 13).
# First matching rule wins; each returns (action_label, query.py need mode).
# The bridge gate is NOT a rule here — bridge_evidence always runs first in
# retrieval, per section 6.8 ("prior knowledge is activated BEFORE new
# instruction"). Mastery/misconception writes stay with the probe/bridge APIs.
# ---------------------------------------------------------------------------


def rules_decide(update: dict, signals: list, flags: list, abstained: bool,
                 acknowledged: bool = False, clarification: bool = False) -> tuple[str, str, str]:
    s = set(signals)
    # rule 1b (deterministic, outranks the inferred-misconception probe): the
    # student EXPLICITLY signalled they did not understand / it is too hard / we
    # are repeating ourselves. Re-explain the SAME idea more simply — never answer
    # a confused learner with a Socratic challenge, and never re-serve a probe they
    # just said they could not follow (learning_log repetition + mis-grade regression).
    if clarification and not acknowledged:
        return "EXPLAIN", "explain", \
            "rule 1b: learner did not understand -> re-explain more simply (no challenge, no re-probe)"
    if "misconception_suspected" in flags:
        return "MISCONCEPTION_PROBE", "explain", "rule 2: probe before correcting (section 13 rule 8)"
    if "hint_requested" in flags:
        return "ANALOGOUS_EXAMPLE", "schema", "rule 3: hint asked -> schema + analogous example, never the answer (rule 10)"
    # PURE acknowledgment ("yes, that explained it") with no fresh ask:
    # consolidate and move forward — NEVER re-explain (debug_text.txt
    # regression). The deterministic cue outranks the classifier here because
    # the classifier misreads acks as confusion (no positive-ack training data).
    if acknowledged:
        return "METACOGNITIVE_REFLECT", "reflect", \
            "rule 2b: understanding confirmed -> reflect + advance, never re-explain (rule 11)"
    if update["cognitive_load"] >= 0.7 or update["frustration_risk"] >= 0.6:
        return "ENCOURAGE", "explain", "rule 4: high load/frustration -> simple explanation + encouragement (rule 2/7)"
    if "transfer_ready_evidence" in flags or "ready_for_next" in s:
        return "TRANSFER_PROBLEM", "transfer", "rule 5: transfer readiness -> near transfer first (section 6.6)"
    if s & {"request_representation", "representation_shift", "graphical", "diagrammatic"}:
        return "REPRESENTATION_TRANSLATION", "integrate", "rule 6: representation gap -> translate (rule 5, KI)"
    if "self_corrected" in flags:
        return "METACOGNITIVE_REFLECT", "reflect", "rule 9: self-correction -> reflection prompt (rule 11)"
    if "example_request" in s:
        return "WORKED_EXAMPLE", "example", "rule 8: example asked -> worked example"
    if update["curiosity"] >= 0.6 and update["confusion"] < 0.4:
        return "SOCRATIC_Q", "challenge", "rule 7: curious + not confused -> challenge (CT)"
    if update["confusion"] >= 0.4:
        return "EXPLAIN", "explain", "rule 10a: confusion default -> explain simply"
    if abstained and not acknowledged:
        return "EXPLAIN", "explain", "rule 10a: unresolved + no clear signal -> explain simply"
    return "QUIZ", "practice", "rule 10b: no distress signal -> practice in ZPD"


# ---------------------------------------------------------------------------
# Local MiniLM chunk index (built once, reused)
# ---------------------------------------------------------------------------


def load_chunk_index(chunks: list, embedder) -> np.ndarray:
    CHUNK_INDEX_DIR.mkdir(parents=True, exist_ok=True)
    emb_path = CHUNK_INDEX_DIR / "chunk_embeddings.npy"
    ids_path = CHUNK_INDEX_DIR / "chunk_ids.json"
    ids = [c["chunk_id"] for c in chunks]
    if emb_path.exists() and ids_path.exists():
        if json.loads(ids_path.read_text(encoding="utf-8")) == ids:
            return np.load(emb_path)
    print(f"building local MiniLM index for {len(chunks)} chunks (one-time)…")
    emb = np.asarray(
        embedder.encode([c.get("text") or "" for c in chunks], batch_size=256,
                        normalize_embeddings=True, show_progress_bar=True),
        dtype=np.float32,
    )
    np.save(emb_path, emb)
    ids_path.write_text(json.dumps(ids), encoding="utf-8")
    return emb


# ---------------------------------------------------------------------------
# Qwen response layer — composes ONLY from manifest items (section 13 rule 12)
# ---------------------------------------------------------------------------


def qwen_chat(prompt: str, temperature: float = 0.4, max_tokens: int = 400) -> str:
    resp = requests.post(
        f"{QWEN}/v1/chat/completions",
        json={"model": "qwen2.5-3b-instruct",
              "messages": [{"role": "user", "content": prompt}],
              "temperature": temperature, "max_tokens": max_tokens},
        timeout=240,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def qwen_answer(question: str, action: str, evidence_blocks: list[dict], chapter_hint: str,
                writeback_note: str = "", history: list[dict] | None = None,
                answer_budget: dict | None = None, figure_on_screen: bool = False,
                clarify: bool = False) -> str:
    tone = {
        "ENCOURAGE": "The student is frustrated or overloaded. Be warm and brief; acknowledge effort first.",
        "MISCONCEPTION_PROBE": "Ask the diagnostic question from the evidence FIRST. Do not reveal the correction yet.",
        "SOCRATIC_Q": "Respond mainly with one guiding question; do not lecture.",
        "METACOGNITIVE_REFLECT": "The student just confirmed understanding. One short reflection question "
                                 "(e.g. 'explain it back in your own words') OR offer the next step. "
                                 "Do NOT re-explain anything already covered.",
    }.get(action, "Teach clearly and briefly at Class 10 level.")
    hist_text = ""
    if history:
        hist_text = "RECENT CONVERSATION (do not repeat explanations already given here; build on them):\n" + \
            "\n".join(f"{h['role'].upper()}: {h['text']}" for h in history) + "\n\n"
    ev_text = "\n\n".join(
        f"EVIDENCE {i + 1}:\n{b['text'][:700]}" for i, b in enumerate(evidence_blocks) if b["text"]
    )[:6000]
    pacing = ""
    max_tokens = 400
    if answer_budget:
        max_words = int(answer_budget.get("max_words", 35))
        max_sentences = int(answer_budget.get("max_sentences", 2))
        micro = answer_budget.get("micro_check_type", "yes_no")
        must_end = answer_budget.get("must_end_with", "micro_check")
        # Token cap is generous enough to let Qwen FINISH its sentences (a too-tight
        # cap cuts mid-sentence and the fragment gets spoken). Real brevity is
        # enforced by _truncate_to_spoken_budget below, which keeps only whole
        # sentences within the word budget.
        max_tokens = max(70, min(180, round(max_words * 3.0)))
        pacing = (
            "PACING CONTRACT FOR SPOKEN VOICE:\n"
            f"- Speak at most {max_words} words and {max_sentences} sentence(s).\n"
            "- Teach ONE complete atomic idea and actually DELIVER it in this reply.\n"
            "- Do NOT announce what you will do ('let's look at an example', 'let me "
            "explain'); just do it. Spend your words on the maths, not on preamble.\n"
            "- If you use an example, WORK IT OUT here: substitute the numbers and carry "
            "the calculation through to the final result (you may do the arithmetic "
            "yourself, e.g. D = (-4)^2 - 4*2*2 = 0). Do not stop at the formula, and "
            "never mention an example without giving it.\n"
            "- Use short, concrete sentences for a Class 10 student.\n"
            "- Do not repeat an explanation already present in RECENT CONVERSATION.\n"
        )
        if must_end == "micro_check" and action not in {"MISCONCEPTION_PROBE", "TRANSFER_PROBLEM", "QUIZ"}:
            micro_phrase = {
                "yes_no": "a short yes-or-no question",
                "own_words": "a short request to say it back in their own words",
                "answer": "a short question asking them to try the answer",
                "question": "one short guiding question",
                "try_step": "a short nudge to try the next step",
                "next_step": "a short check on what to do next",
            }.get(micro, "a short question")
            pacing += (
                f"- End with {micro_phrase}, but ONLY about what you actually explained "
                "in THIS reply. Never ask 'did you understand' about something you did not "
                "show. If you worked an example, ask them to state the result or try the "
                "next step.\n"
                "- Do NOT print any label like 'yes_no:' or 'check:'; just ask the question.\n"
                "- This is only for pacing, not for grading mastery.\n"
            )
        else:
            pacing += "- Do not add an extra pacing question after the required diagnostic/problem.\n"
        pacing += "\n"
    clarify_cue = ""
    if clarify:
        clarify_cue = (
            "THE STUDENT SAID THEY DID NOT UNDERSTAND YOUR PREVIOUS REPLY (or that you "
            "are repeating yourself). Explain the SAME idea a DIFFERENT, simpler way: "
            "shorter sentences, plainer words, and a concrete number example. Do NOT "
            "repeat your earlier wording or ask the same question again.\n"
        )
    screen_cue = ""
    if figure_on_screen:
        screen_cue = (
            "A FIGURE FROM THE TEXTBOOK IS BEING SHOWN ON THE STUDENT'S SCREEN RIGHT NOW. "
            "Refer to it directly ('look at the figure on the screen', 'in the picture you "
            "can see…') and use it to make your point. Do NOT describe the picture in words "
            "as if they cannot see it — point them to it.\n"
        )
    prompt = (
        f"You are Wini, a friendly Class 10 Maths tutor ({chapter_hint}).\n"
        f"Pedagogical action for this turn: {action}. {tone}\n"
        + (f"Context: {writeback_note}\n" if writeback_note else "")
        + clarify_cue
        + screen_cue
        + pacing
        + "Use ONLY the evidence below — if it does not support a claim, say less. "
        "Never mention internal IDs, codes, or evidence numbers (no 'jemh104', no "
        "'EVIDENCE 2', no 'misconception::...'); speak naturally about the maths. "
        "Indian-English friendly.\n\n"
        f"{hist_text}{ev_text}\n\nSTUDENT: {question}\n\nWINI:"
    )
    text = qwen_chat(prompt, temperature=0.3, max_tokens=max_tokens)
    if answer_budget:
        text = _truncate_to_spoken_budget(
            text,
            int(answer_budget.get("max_words", 35)),
            int(answer_budget.get("max_sentences", 2)),
        )
    return text


def _budget_for_generation(answer_budget: dict | None, action: str) -> dict | None:
    """Resize the spoken budget to the ACTUAL pedagogical action.

    The pacing layer guesses a generic budget before the action is decided, so a
    WORKED_EXAMPLE would otherwise be capped at EXPLAIN's 35 words / 2 sentences —
    only enough to announce an example, not work it. We take the per-action word/
    sentence room from the pacing controller (single source of truth) while keeping
    the caller's micro-check decision (must_end_with reflects pending_check state).
    """
    if not answer_budget:
        return answer_budget
    try:
        from pacing.pacing_controller import ACTION_BUDGETS
        ab = ACTION_BUDGETS.get(action)
    except Exception:  # noqa: BLE001 — pacing not importable: keep caller's budget
        ab = None
    if not ab:
        return answer_budget
    out = dict(answer_budget)
    out["max_words"] = int(ab["max_words"])
    out["max_sentences"] = int(ab["max_sentences"])
    # adopt the action's check type (e.g. WORKED_EXAMPLE -> 'try_step', so the model
    # asks them to try the next step rather than 'did you understand'); but keep the
    # caller's must_end_with, which already encodes pending_check (no extra check).
    if out.get("must_end_with") == "micro_check":
        out["micro_check_type"] = ab.get("micro_check_type", out.get("micro_check_type"))
    return out


def _truncate_to_spoken_budget(text: str, max_words: int, max_sentences: int) -> str:
    """Enforce the spoken budget on Qwen's output for TTS.

    Keeps only COMPLETE sentences (this also drops a trailing fragment left by a
    token-capped generation, e.g. '...4 times 2' with no period). Then caps to
    max_sentences and to max_words, always keeping at least one sentence and
    preserving a trailing micro-check question if there is one.
    """
    import re as _re

    sentences = [s.strip() for s in _re.findall(r"[^.!?]*[.!?]", text.strip()) if s.strip()]
    if not sentences:
        # no terminator at all (rare) — return the raw text, trimmed of any
        # obvious dangling open paren from a hard token cut.
        return text.strip().rstrip("(,-")
    kept: list[str] = []
    words = 0
    for s in sentences[:max_sentences]:
        w = len(s.split())
        if kept and words + w > max_words:
            break
        kept.append(s)
        words += w
    last = sentences[-1]
    if last.endswith("?") and not kept[-1].endswith("?"):
        # ensure the pacing micro-check survives the cap
        if words + len(last.split()) > max_words and len(kept) > 1:
            kept[-1] = last
        elif last not in kept:
            kept.append(last)
    return " ".join(kept)


def qwen_cohesion_check(evidence: list[dict], blocks_text: dict) -> list[str]:
    """A1.5 LLM half, local: when the bundle mixes >= 3 source types, ask Qwen
    whether any items contradict each other. Returns ids to drop (only
    chunk/figure items are droppable — diagnostics and bridges are protected).
    Any failure returns [] so the judge can never break retrieval."""
    types = {e["type"] for e in evidence}
    if len(types) < 3:
        return []
    droppable = [e for e in evidence if e["type"] in ("chunk", "figure")]
    if not droppable:
        return []
    listing = "\n".join(f"- id={e['id']}: {blocks_text.get(e['id'], '')[:200]}" for e in evidence
                        if blocks_text.get(e["id"]))
    prompt = (
        "These snippets will be combined into ONE maths tutoring reply. "
        "Do any DIRECTLY contradict each other (state incompatible facts)?\n"
        f"{listing}\n\n"
        'Respond with ONLY JSON: {"contradicting_ids": []} — list ids ONLY for true contradictions, '
        "not mere topic differences. Usually the list is empty."
    )
    try:
        import re as _re
        text = qwen_chat(prompt, temperature=0.0, max_tokens=120)
        m = _re.search(r"\[.*?\]", text, _re.DOTALL)
        if not m:
            return []
        flagged = set(json.loads(m.group(0)))
        return [e["id"] for e in droppable if e["id"] in flagged]
    except Exception:  # noqa: BLE001
        return []


def judge_answer(question: str, expected: str, student_answer: str) -> str:
    """Grade a diagnostic answer with the local Qwen model.

    Returns correct | partial | wrong | not_an_answer. Any failure (server
    down, unparseable output) degrades to not_an_answer so learner state is
    never moved by a broken grader.
    """
    prompt = (
        "You are grading a Class 10 maths check question.\n"
        f"QUESTION: {question}\n"
        f"EXPECTED ANSWER: {expected}\n"
        f"STUDENT REPLY: {student_answer}\n\n"
        'Classify the student reply. Respond with ONLY one JSON object like {"outcome": "correct"}.\n'
        "outcome must be one of: correct (matches expected), partial (right direction, "
        "incomplete or with an error), wrong (contradicts expected), not_an_answer "
        "(the reply does not attempt the question — e.g. a new question, topic change, or 'i dont know')."
    )
    try:
        text = qwen_chat(prompt, temperature=0.0, max_tokens=40)
        import re as _re
        m = _re.search(r'"outcome"\s*:\s*"(correct|partial|wrong|not_an_answer)"', text)
        if m:
            return m.group(1)
        m = _re.search(r"\b(correct|partial|wrong|not_an_answer)\b", text.lower())
        return m.group(1) if m else "not_an_answer"
    except Exception:  # noqa: BLE001
        return "not_an_answer"


# ---------------------------------------------------------------------------
# One turn
# ---------------------------------------------------------------------------


class TutorLoop:
    def __init__(self, state_path: Path = ROOT / "learner_state.json", want_answer: bool = True,
                 use_judge: bool = True):
        self.use_judge = use_judge
        self.chunks, self.concepts, self.graph, _ = load_store(STORE)
        self.concepts_by_id = {c["concept_id"]: c for c in self.concepts}
        self.chunks_by_id = {c["chunk_id"]: c for c in self.chunks}
        self.figure_misconceptions = {
            n: (a.get("disambiguates_misconceptions") or [])
            for n, a in self.graph.nodes(data=True) if a.get("image_path")
        }
        self.analyzer = CognitiveAnalyzer()
        self.shadow = PolicyShadow.load()
        # HOPE detector shares the analyzer's MiniLM embedder (one model in VRAM)
        self.hope = HopeDetector.load()
        self.hope.embedder = self.analyzer.classifier.embedder
        self.state = load_learner_state(state_path)
        self.chunk_emb = load_chunk_index(self.chunks, self.analyzer.classifier.embedder)
        self.want_answer = want_answer

    # which need mode serves which HOPE signal probe
    NEED_TO_HOPE = {"challenge": "CT", "transfer": "KT", "integrate": "KI"}
    HOPE_EV_TYPES = {"ct_probe": "CT", "transfer_target": "KT", "integration_target": "KI"}

    # T9 multimodal display channel: actions that are themselves visual, for which
    # an incidental figure-caption crop is worth SHOWING even when no pedagogy-gated
    # `figure` crop was selected (architecture section 9 "show, don't only tell").
    VISUAL_ACTIONS = {"REPRESENTATION_TRANSLATION", "VISUAL_ANALOGY"}

    @property
    def current_concept(self):
        return self.state.data.setdefault("session", {}).get("current_concept")

    def analyze_only(self, text: str) -> dict:
        """Analyze a student utterance without mutating learner state.

        Used by the voice pacing layer to triage mixed replies before the normal
        turn path decides which state channels may move.
        """
        return self.analyzer.analyze(text, current_concept=self.current_concept)

    def _build_display(self, evidence: list[dict], action: str) -> list[dict]:
        """T9 multimodal channel — pick at most ONE task-relevant figure crop to
        SHOW alongside speech (working-memory limit: one primary visual per turn).

        query.py already gates `figure`-type evidence to exactly the two
        pedagogical show-cases — a representation gap (need_evidence/integrate:
        ``reps_missing & supports_representation``) or disambiguating an active
        misconception (misconception_evidence corrective phase) — so any
        figure-type item is show-worthy. An *incidental* `figure_caption` chunk
        (a semantic match that happens to carry a crop) is shown only when the
        action is itself visual (REPRESENTATION_TRANSLATION / VISUAL_ANALOGY).
        Otherwise the turn stays audio-only and this returns [].

        Items are channel-agnostic: ``image_path`` stays store-relative so each
        DisplaySink (web /store route, Windows pane, Jetson /display_image)
        resolves it against the store root — never hard-coded.
        """
        primary = None    # pedagogy-gated `figure` crop (preferred)
        fallback = None   # incidental figure_caption chunk (visual actions only)
        for e in evidence:
            if not e.get("image_path"):
                continue
            if e["type"] == "figure":
                primary = e
                break
            if e["type"] == "chunk" and action in self.VISUAL_ACTIONS and fallback is None:
                fallback = e
        chosen = primary or fallback
        if not chosen:
            return []
        node = self.graph.nodes.get(chosen["id"], {})
        row = self.chunks_by_id.get(chosen["id"], {})
        alt = (chosen.get("alt_text") or node.get("alt_text")
               or (row.get("text") or "").split(":")[0].strip()[:120] or "figure")
        supports = (chosen.get("supports_representation") or node.get("supports_representation")
                    or row.get("representations") or [])
        return [{
            "image_path": chosen["image_path"],   # store-relative; sink resolves
            "alt_text": alt,
            "why": chosen.get("why", ""),
            "supports_representation": supports,
            "figure_id": chosen["id"],
        }]

    def turn(self, text: str, answer_budget: dict | None = None,
             precomputed_analysis: dict | None = None) -> dict:
        # 1-2. cognitive analysis + state update (Parts 1+2+3)
        if precomputed_analysis is None:
            analysis = self.analyzer.analyze_and_apply(text, self.state, current_concept=self.current_concept)
        else:
            from cognitive_analyzer.analyzer import apply_deltas

            analysis = precomputed_analysis
            analysis["new_global_state"] = apply_deltas(self.state, analysis["state_deltas"])
        concept = analysis["concept"]
        primary = concept["concept_id"]
        if primary:
            self.state.data.setdefault("session", {})["current_concept"] = primary

        # 1a. Is this reply an ATTEMPT at the question we asked, or a non-attempt
        # (acknowledgment, "I don't understand", a fresh request, a counter-
        # question)? Computed once and reused by the diagnostic grader (1b),
        # the HOPE scorer (1c) and the pedagogy rules so a confusion plea is
        # never written back as a "wrong" diagnostic answer (learning_log
        # regression: "i can not understand" graded wrong → mastery dropped).
        from cognitive_classifier.cues import (
            is_pure_ack, is_question, is_clarification_request, is_answer_attempt,
        )
        _sig = set(analysis["signals"])
        _norm = analysis["normalized_text"]
        clarification = is_clarification_request(text) or "simplification_request" in _sig
        answer_try = ("answer_attempt" in _sig) or is_answer_attempt(text)
        wants_hint = ("hint_requested" in analysis["state_deltas"]["concept_flags"]
                      or "request_hint" in _sig)
        fresh_request = wants_hint or bool(_sig & {
            "request_representation", "representation_shift",
            "simplification_request", "example_request", "topic_shift"})
        # a non-attempt carries no answer cue AND looks like an ack / confusion plea /
        # bare question / fresh request rather than a try at the pending question
        non_attempt = (not answer_try) and (
            is_pure_ack(_norm) or clarification or is_question(text) or fresh_request)

        # 1b. pending diagnostic from the previous turn (closed loop, section 8):
        # a hint request escalates the hint chain (never past it, rule 10); any
        # other reply is graded by Qwen and written back via the evidence APIs.
        session = self.state.data.setdefault("session", {})
        pending = session.get("pending_check")
        writeback = None
        if pending:
            wants_hint = "hint_requested" in analysis["state_deltas"]["concept_flags"] \
                or "request_hint" in analysis["signals"]
            chain = pending.get("hint_chain") or []
            if wants_hint and chain:
                k = self.state.record_hint_request(pending["concept_id"], pending["id"])
                if k <= len(chain):
                    hint = chain[k - 1]
                    hint_text = hint.get("text") if isinstance(hint, dict) else str(hint)
                    self._log(text, f"HINT_LEVEL_{k}", "rule 10: fade one hint level, never the answer",
                              "hint", None, analysis, {"evidence": [ev(pending["id"], "hint",
                                                                       f"hint level {k} of pending diagnostic",
                                                                       text=hint_text)]})
                    if self.state.path:
                        self.state.save()
                    return {"action": f"HINT_LEVEL_{k}", "action_reason": "hint chain level served",
                            "need": "hint", "shadow": None, "concept": concept,
                            "signals": analysis["signals"], "cognitive_update": analysis["cognitive_update"],
                            "n_evidence": 1, "bridge_ids": [], "display": [], "answer": hint_text}
                # chain exhausted: fall through — rule 10 says switch action, don't leak
            # Only grade a reply that actually ATTEMPTS the question. A non-attempt
            # (ack, "I don't understand", a fresh request, a counter-question) must
            # never move mastery or force a misconception active — the weak local
            # judge otherwise returns "wrong" for plain confusion (see 1a).
            if non_attempt:
                outcome = "not_an_answer"
            else:
                outcome = judge_answer(pending["question"], pending["expected_answer"], text) \
                    if self.want_answer else "not_an_answer"
            if outcome in ("correct", "partial", "wrong"):
                hints_used = (self.state.concept_states.get(pending["concept_id"]) or {}) \
                    .get("hints_used_current", 0)
                if pending["kind"] == "bridge":
                    writeback = self.state.apply_bridge_result(pending["id"], outcome)
                else:
                    writeback = self.state.apply_probe_result(
                        pending["id"], outcome, concept_id=pending["concept_id"], hints_used=hints_used)
                writeback["graded_reply"] = text
            session.pop("pending_check", None)

        # 1c. pending HOPE probe from the previous turn (Part 4 wired live): if
        # the tutor served a CT/KT/KI probe last turn and the student attempted
        # an answer, score it 0-3 with the HOPE detector and fold into the
        # rolling KI/KT/CT averages (consumed by query.py ranking w7).
        hope_update = None
        pending_hope = session.get("pending_hope")
        if pending_hope:
            # only score a substantive attempt at the probe — a non-attempt
            # (ack / confusion plea / fresh request / counter-question) must not
            # be scored 0 and drag the rolling HOPE average down (see 1a)
            attempted = (not non_attempt) and len(text.split()) >= 4
            if attempted:
                r = self.hope.score(pending_hope["signal"], pending_hope["prompt"],
                                    text, pending_hope.get("rubric_anchor", ""))
                rolling = self.state.update_hope(pending_hope["signal"], r["score"])
                hope_update = {"signal": pending_hope["signal"], "label": r["label"],
                               "score": r["score"], "rolling": rolling}
            session.pop("pending_hope", None)

        # 2b. acknowledgment handling + representation write-back (v3): a
        # confirmed REPRESENTATION_TRANSLATION marks the served representations
        # as known for the session concept (architecture section 9 coverage)
        from cognitive_classifier.cues import is_pure_ack
        acknowledged = is_pure_ack(analysis["normalized_text"])
        if acknowledged and primary and session.get("last_action") == "REPRESENTATION_TRANSLATION":
            cs = self.state.concept_states.setdefault(primary, {})
            known = cs.setdefault("representations_known", [])
            for rep in session.get("last_repr_targets", []):
                if rep and rep not in known:
                    known.append(rep)

        # 3. pedagogy: rules decide, shadow suggests (logged only)
        action, need, why = rules_decide(
            analysis["cognitive_update"], analysis["signals"],
            analysis["state_deltas"]["concept_flags"], concept["abstained"],
            acknowledged=acknowledged,
            clarification=(clarification and not answer_try),
        )
        shadow = self.shadow.suggest(analysis, self.analyzer.classifier)

        # 4. retrieval over the local index, reusing query.py machinery
        concept_hits = [{"concept_id": primary, "score": concept["concept_confidence"]}] if primary else []
        concept_hits += [{"concept_id": c, "score": 0.3} for c in concept.get("secondary_concepts", [])]
        concept_ids = [h["concept_id"] for h in concept_hits]
        band, band_reason = resolve_band(concept_hits, self.state, None)
        snapshot = Snapshot(self.state, primary, self.concepts_by_id.get(primary), self.graph, band)

        evidence: list[dict] = []
        evidence += bridge_evidence(self.graph, self.chunks_by_id, snapshot, concept_ids,
                                    force=(need == "bridge"))
        evidence += misconception_evidence(self.graph, snapshot)
        evidence += need_evidence(self.graph, self.concepts_by_id, snapshot, need, None)

        # candidate probe: the analyzer suspects a misconception but none is
        # active in state yet — serve the concept's first untracked
        # misconception diagnostic (probe before correcting, rule 8)
        if action == "MISCONCEPTION_PROBE" and primary and primary in self.graph \
                and not any(e["type"] == "misconception" for e in evidence):
            # concept-card `misconceptions` are free text; the nodes hang off the
            # concept via has_misconception edges
            for _, mid, d in self.graph.out_edges(primary, data=True):
                if d.get("relation") != "has_misconception":
                    continue
                if self.state.misconception_status(mid) not in ("untracked", "weakening"):
                    continue
                a = self.graph.nodes[mid]
                if a.get("diagnostic_question"):
                    evidence.insert(0, ev(mid, "misconception",
                                          "suspected via analyzer; diagnostic served (probe-first)",
                                          diagnostic_question=a.get("diagnostic_question"),
                                          hint_chain=a.get("hint_chain")))
                    break

        # arm the pending check for the NEXT turn: first diagnostic served wins
        # (bridges precede misconceptions in evidence order, matching section 6.8).
        # ONLY the two mastery-grading diagnostics may arm it — a `ct_probe` also
        # carries a `question`, but CT/KT/KI probes are scored by the HOPE path
        # (pending_hope) and must NOT be graded as misconceptions: doing so wrote
        # a bogus `ct_probe::...` entry into misconception_states and moved mastery
        # (learning_log regression — a Socratic turn tanked quadratic_zero_geometry).
        for e in evidence:
            if e["type"] not in ("bridge_diagnostic", "misconception"):
                continue
            q = e.get("question") or e.get("diagnostic_question")
            if not q:
                continue
            node = self.graph.nodes.get(e["id"], {})
            session["pending_check"] = {
                "kind": "bridge" if e["type"] == "bridge_diagnostic" else "misconception",
                "id": e["id"], "concept_id": primary or e.get("target_concept"),
                "question": q, "expected_answer": node.get("expected_answer", ""),
                "hint_chain": e.get("hint_chain") or node.get("hint_chain"),
            }
            break

        candidates_idx = [i for i, r in enumerate(self.chunks)
                          if any(c in (r.get("concept_ids") or []) for c in concept_ids)] \
            or list(range(len(self.chunks)))
        q_emb = self.analyzer.classifier.embed([analysis["normalized_text"]])
        sims = (q_emb @ self.chunk_emb[candidates_idx].T)[0]
        order = np.argsort(-sims)[:24]
        ranked = [dict(self.chunks[candidates_idx[j]], score=float(max(sims[j], 0.0))) for j in order]
        top, trace = snapshot_rerank(ranked, snapshot, need, 6, self.figure_misconceptions)
        for r in top:
            evidence.append(ev(r["chunk_id"], "chunk",
                               f"local semantic+pedagogic match (role={r.get('pedagogical_role')})",
                               image_path=r.get("image_path") if r.get("kind") == "figure_caption" else None))
        cohesion_log = cohesion_filter(self.graph, evidence, self.chunks, concept_ids,
                                       band[2], None, use_judge=False)
        # v3: local Qwen contradiction judge (cost-gated to >= 3 evidence types)
        if self.use_judge and self.want_answer:
            blocks_text = {}
            for e in evidence:
                row = self.chunks_by_id.get(e["id"])
                blocks_text[e["id"]] = (row or {}).get("text") or e.get("text") \
                    or e.get("question") or e.get("why_wrong") or ""
            dropped = qwen_cohesion_check(evidence, blocks_text)
            if dropped:
                evidence = [e for e in evidence if e["id"] not in dropped]
                cohesion_log = (cohesion_log or []) + [f"qwen_judge dropped: {dropped}"]

        manifest = {
            "evidence": evidence,
            "bridge_ids": [e["id"] for e in evidence if e["type"].startswith("bridge")],
            "schema_ids": [e["id"] for e in evidence if e["type"] == "problem_schema"],
            "ranking_trace": trace, "cohesion_log": cohesion_log,
            "snapshot": snapshot.summary(), "band_reason": band_reason,
        }

        # 4b. T9 display channel: pick the one figure crop (if any) to SHOW this
        # turn. Computed before generation so the prompt can reference it on screen.
        display = self._build_display(evidence, action)

        # 5. response from manifest only (Qwen, local)
        answer = None
        if self.want_answer:
            blocks = []
            for e in evidence:
                row = self.chunks_by_id.get(e["id"])
                txt = (row or {}).get("text") or e.get("text") or e.get("question") \
                    or e.get("why_wrong") or e.get("prompt") or e.get("note") or ""
                blocks.append({"source_path": e["id"], "text": txt})
            chapter_hint = "Class 10 Mathematics"
            if primary:
                doc = self.graph.nodes.get(primary, {}).get("chapter_doc")
                chap = self.graph.nodes.get(f"chapter::{doc}", {}) if doc else {}
                if chap.get("name"):
                    chapter_hint += f", Chapter: {chap['name']}"
            note = ""
            if writeback:
                note = (f"The student just answered the previous check question: outcome was "
                        f"'{writeback['outcome']}'. "
                        + ("Acknowledge it and continue." if writeback["outcome"] == "correct"
                           else "Gently correct using the evidence; do not scold."))
            # The pacing layer computed answer_budget BEFORE the action was known
            # (generic EXPLAIN). Now that the action is decided, give the generator
            # the action-appropriate word/sentence room — e.g. a WORKED_EXAMPLE
            # needs space to actually work the example, not just announce it.
            gen_budget = _budget_for_generation(answer_budget, action)
            answer = qwen_answer(text, action, blocks, chapter_hint, writeback_note=note,
                                 history=session.get("context", [])[-6:],
                                 answer_budget=gen_budget, figure_on_screen=bool(display),
                                 clarify=(clarification and not answer_try))

        # 6. session memory (section 12.3 transient context) + bookkeeping for
        # the next turn's acknowledgment handling
        ctx = session.setdefault("context", [])
        ctx.append({"role": "student", "text": text[:250]})
        if answer:
            ctx.append({"role": "wini", "text": answer[:250]})
        session["context"] = ctx[-8:]
        session["last_action"] = action
        session["last_repr_targets"] = sorted({
            rep for e in evidence
            for rep in (e.get("supports_representation") or [])
        }) if action == "REPRESENTATION_TRANSLATION" else []

        # arm a HOPE probe for next-turn scoring if this turn served a CT/KT/KI
        # probe (the student answers Qwen's posed question, so for transfer/
        # integration the generated answer text is the prompt; ct_probe carries
        # its own stored question + expected_insight rubric)
        hope_signal = self.NEED_TO_HOPE.get(need)
        probe_ev = next((e for e in evidence if self.HOPE_EV_TYPES.get(e["type"]) == hope_signal), None) \
            if hope_signal else None
        if probe_ev:
            session["pending_hope"] = {
                "signal": hope_signal,
                "id": probe_ev["id"],
                "prompt": probe_ev.get("question") or (answer or "")[:500],
                "rubric_anchor": probe_ev.get("expected_insight") or probe_ev.get("note") or "",
            }

        # 7. log + persist (section 12.2; rules + shadow logged side by side)
        self._log(text, action, why, need, shadow, analysis, manifest, writeback, hope_update)
        self.state.mark_served([e["id"] for e in evidence])
        if self.state.path:
            self.state.save()

        return {"action": action, "action_reason": why, "need": need, "shadow": shadow,
                "concept": concept, "signals": analysis["signals"],
                "cognitive_update": analysis["cognitive_update"],
                "n_evidence": len(evidence), "bridge_ids": manifest["bridge_ids"],
                "writeback": writeback, "hope_update": hope_update,
                "pending_check": session.get("pending_check", {}).get("id"),
                "pending_hope": session.get("pending_hope", {}).get("signal"),
                "answer_budget": answer_budget,
                "pace": session.get("pace", {}),
                "display": display,
                "answer": answer}

    def _log(self, text, action, why, need, shadow, analysis, manifest, writeback=None,
             hope_update=None) -> None:
        concept = analysis["concept"]
        log_row = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S"), "loop": "tutor_loop_v4",
            "question": text, "action": action, "action_reason": why, "need": need,
            "shadow_suggestion": shadow, "signals": analysis["signals"],
            "cognitive_update": analysis["cognitive_update"],
            "concept": {k: concept[k] for k in ("concept_id", "concept_confidence", "abstained")},
            "writeback": writeback, "hope_update": hope_update,
            "manifest": manifest,
        }
        with open(STORE / "learning_log.jsonl", "a", encoding="utf-8") as f:
            f.write(json.dumps(log_row, ensure_ascii=False) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--once", default=None, help="run a single turn and print JSON")
    ap.add_argument("--state", default=str(ROOT / "learner_state.json"))
    ap.add_argument("--no-answer", action="store_true", help="skip Qwen generation")
    ap.add_argument("--no-judge", action="store_true", help="disable the Qwen cohesion judge")
    args = ap.parse_args()

    loop = TutorLoop(state_path=Path(args.state), want_answer=not args.no_answer,
                     use_judge=not args.no_judge)
    if args.once:
        out = loop.turn(args.once)
        print(json.dumps(out, indent=2, ensure_ascii=False))
        return
    print("Wini tutor loop (local MiniLM + Qwen). Ctrl+C or 'quit' to exit.")
    while True:
        try:
            text = input("\nyou> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if not text or text.lower() in {"quit", "exit"}:
            break
        out = loop.turn(text)
        print(f"[{out['action']} | {out['concept']['concept_id']} | {out['n_evidence']} evidence"
              f" | shadow: {out['shadow']['action']}]")
        if out["answer"]:
            print(f"wini> {out['answer']}")


if __name__ == "__main__":
    main()
