"""Tutor loop v1 (build plan Part 7, architecture section 7) — fully local.

Wires the runtime described in architecture section 19:

    student text
    -> CognitiveAnalyzer (Part 1 classifier + Part 2 resolver, MiniLM, local)
    -> learner state update (EMA globals + flags)
    -> rule-based pedagogy decision (v1 rules below) + PolicyShadow suggestion (logged)
    -> evidence retrieval reusing query.py's machinery (bridge gate, misconception
       probe-first mechanics, need evidence, 7-term snapshot rerank, cohesion check)
       over a LOCAL MiniLM chunk index (the Gemini FAISS index is not touched)
    -> response generated by the LOCAL Qwen model (llama.cpp server, GPU)
       composed ONLY from manifest items
    -> learning_log.jsonl append + state save

No cloud calls anywhere: embeddings are MiniLM, generation is Qwen. Start the
llama server first:
    python F:/Projects/Pedagogical_study_pkg/scripts/run_llama_server.py

Usage:
    python tutor_loop.py                      # interactive chat
    python tutor_loop.py --once "message"     # single scripted turn (for tests)
    python tutor_loop.py --once "..." --no-answer   # skip Qwen generation
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

import numpy as np
import requests

from cognitive_analyzer import CognitiveAnalyzer
from hope_detector import HopeDetector
from learner_state import COLD_START_MASTERY, load_learner_state
from policy_shadow import PolicyShadow
from query import (
    Snapshot,
    bridge_evidence,
    cohesion_filter,
    ev,
    load_store,
    misconception_evidence,
    need_evidence,
    resolve_band,
    snapshot_rerank,
)

ROOT = Path(__file__).resolve().parent
STORE = ROOT / "rag_store"
CHUNK_INDEX_DIR = ROOT / "models" / "local_chunk_index"
QWEN = "http://127.0.0.1:8080"

# Generation backend (CLAUDE.md cloud pivot): "qwen" = local llama.cpp server at
# :8080 (legacy/fallback), "gemini" = Vertex Gemini 2.5 Flash via llm_vertex.
# The manifest-grounded prompt is IDENTICAL for both — only the transport changes,
# so every qwen_chat call site (answer, cohesion judge, grader) switches at once.
GEN_BACKEND = os.getenv("GEN_BACKEND", "qwen").strip().lower()

# Perception (Part 11, PART11_GEMINI_PERCEPTION_LAYER.md): ONE structured Gemini
# call (intent + signals + concept). Promoted Stage 4 (2026-07-02); the local
# MiniLM heads were retired from the runtime path at Stage 6 — artifacts stay on
# disk as the eval baseline, and the learning-path fallback on a failed Gemini
# call is gates + inherit-concept + neutral signals (a turn never hard-fails).
# The deterministic SAFETY/NONSENSE gates run before any model (§4.2).
from perception import gate as _front_gate  # noqa: E402  (model-free, cheap regex)
from perception.config import PERCEPTION_BACKEND  # noqa: E402

# ---------------------------------------------------------------------------
# Rule-based pedagogy decision v1 (architecture section 6.6 / section 13).
# First matching rule wins; each returns (action_label, query.py need mode).
# The bridge gate is NOT a rule here — bridge_evidence always runs first in
# retrieval, per section 6.8 ("prior knowledge is activated BEFORE new
# instruction"). Mastery/misconception writes stay with the probe/bridge APIs.
# ---------------------------------------------------------------------------


def rules_decide(update: dict, signals: list, flags: list, abstained: bool,
                 acknowledged: bool = False, clarification: bool = False,
                 learning_start: bool = False, visual: bool = False,
                 purpose: bool = False) -> tuple[str, str, str]:
    s = set(signals)
    # rule 1a-vis (deterministic, outranks rule 1b): the student said they cannot
    # PICTURE it ("I cannot imagine this") or asked what it looks like. That is a
    # representation gap, not generic confusion — re-explaining the same words is
    # exactly the failure gemini_tutor_issues.md #3/#4 flagged. Switch modality:
    # a concrete scene / figure (rule 6 machinery, KI need).
    if visual and not acknowledged:
        return "REPRESENTATION_TRANSLATION", "integrate", \
            "rule 1a-vis: learner cannot picture it -> switch representation, never re-define"
    # rule 1w (deterministic): the student asked WHY this is worth learning, what
    # it is for, or HOW something shown connects to the topic — or complained that
    # their question was not answered. ANSWER THAT question; never respond with a
    # new problem or another definition (2026-07-03 transcript: "how is this
    # related to quadratic equation" drew a TRANSFER_PROBLEM, then two deflections
    # until the student gave up).
    if purpose and not acknowledged:
        return "WHY_IT_MATTERS", "explain", \
            "rule 1w: purpose/connection question -> answer the why directly, never deflect"
    # rule 1b (deterministic, outranks the inferred-misconception probe): the
    # student EXPLICITLY signalled they did not understand / it is too hard / we
    # are repeating ourselves. Re-explain the SAME idea more simply — never answer
    # a confused learner with a Socratic challenge, and never re-serve a probe they
    # just said they could not follow (learning_log repetition + mis-grade regression).
    if clarification and not acknowledged:
        return "EXPLAIN", "explain", \
            "rule 1b: learner did not understand -> re-explain more simply (no challenge, no re-probe)"
    # rule 1c (learning start): the student is opening a NEW / never-taught topic and
    # asking to learn it (curiosity / a bare question, no distress, no pending check).
    # Introduce and EXPLAIN it — never QUIZ or Socratically challenge a topic that has
    # not been taught yet (the transcript regression: "I want to learn trigonometry"
    # -> QUIZ "which angle is 90 degrees?").
    if learning_start and not acknowledged:
        return "EXPLAIN", "explain", \
            "rule 1c: fresh topic + wants to learn -> introduce and explain (never quiz first)"
    if "misconception_suspected" in flags:
        return "MISCONCEPTION_PROBE", "explain", "rule 2: probe before correcting (section 13 rule 8)"
    if "hint_requested" in flags:
        return "ANALOGOUS_EXAMPLE", "schema", "rule 3: hint asked -> schema + analogous example, never the answer (rule 10)"
    # PURE acknowledgment ("yes, that explained it") with no fresh ask:
    # consolidate and move forward — NEVER re-explain (debug_text.txt
    # regression). The deterministic cue outranks the classifier here because
    # the classifier misreads acks as confusion (no positive-ack training data).
    if acknowledged:
        return "METACOGNITIVE_REFLECT", "reflect", \
            "rule 2b: understanding confirmed -> reflect + advance, never re-explain (rule 11)"
    if update["cognitive_load"] >= 0.7 or update["frustration_risk"] >= 0.6:
        return "ENCOURAGE", "explain", "rule 4: high load/frustration -> simple explanation + encouragement (rule 2/7)"
    if "transfer_ready_evidence" in flags or "ready_for_next" in s:
        return "TRANSFER_PROBLEM", "transfer", "rule 5: transfer readiness -> near transfer first (section 6.6)"
    if s & {"request_representation", "representation_shift", "graphical", "diagrammatic"}:
        return "REPRESENTATION_TRANSLATION", "integrate", "rule 6: representation gap -> translate (rule 5, KI)"
    if "self_corrected" in flags:
        return "METACOGNITIVE_REFLECT", "reflect", "rule 9: self-correction -> reflection prompt (rule 11)"
    if "example_request" in s:
        return "WORKED_EXAMPLE", "example", "rule 8: example asked -> worked example"
    if update["curiosity"] >= 0.6 and update["confusion"] < 0.4:
        return "SOCRATIC_Q", "challenge", "rule 7: curious + not confused -> challenge (CT)"
    if update["confusion"] >= 0.4:
        return "EXPLAIN", "explain", "rule 10a: confusion default -> explain simply"
    if abstained and not acknowledged:
        return "EXPLAIN", "explain", "rule 10a: unresolved + no clear signal -> explain simply"
    return "QUIZ", "practice", "rule 10b: no distress signal -> practice in ZPD"


# ---------------------------------------------------------------------------
# Local MiniLM chunk index (built once, reused)
# ---------------------------------------------------------------------------


def load_chunk_index(chunks: list, embedder) -> np.ndarray:
    CHUNK_INDEX_DIR.mkdir(parents=True, exist_ok=True)
    emb_path = CHUNK_INDEX_DIR / "chunk_embeddings.npy"
    ids_path = CHUNK_INDEX_DIR / "chunk_ids.json"
    ids = [c["chunk_id"] for c in chunks]
    if emb_path.exists() and ids_path.exists():
        if json.loads(ids_path.read_text(encoding="utf-8")) == ids:
            return np.load(emb_path)
    print(f"building local MiniLM index for {len(chunks)} chunks (one-time)…")
    emb = np.asarray(
        embedder.encode([c.get("text") or "" for c in chunks], batch_size=256,
                        normalize_embeddings=True, show_progress_bar=True),
        dtype=np.float32,
    )
    np.save(emb_path, emb)
    ids_path.write_text(json.dumps(ids), encoding="utf-8")
    return emb


# ---------------------------------------------------------------------------
# Qwen response layer — composes ONLY from manifest items (section 13 rule 12)
# ---------------------------------------------------------------------------


def qwen_chat(prompt: str, temperature: float = 0.4, max_tokens: int = 400) -> str:
    """Single generation seam. Despite the name, dispatches to Gemini Flash when
    GEN_BACKEND=gemini (the CLAUDE.md cloud pivot); the local Qwen server path is
    unchanged when GEN_BACKEND=qwen. Callers pass the same manifest-grounded prompt
    either way."""
    if GEN_BACKEND == "gemini":
        return _gemini_chat(prompt, temperature=temperature, max_tokens=max_tokens)
    resp = requests.post(
        f"{QWEN}/v1/chat/completions",
        json={"model": "qwen2.5-3b-instruct",
              "messages": [{"role": "user", "content": prompt}],
              "temperature": temperature, "max_tokens": max_tokens},
        timeout=240,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def _gemini_chat(prompt: str, temperature: float, max_tokens: int) -> str:
    """Gemini Flash generation via the shared Vertex client (hard wall-clock
    timeout inside llm_vertex). Imported lazily so the default Qwen path pulls in
    no cloud deps. The token floor keeps tiny-cap JSON callers (grader max_tokens=40)
    from being starved once Flash's own overhead is counted."""
    import llm_vertex

    return llm_vertex.generate_reply(
        prompt,
        temperature=temperature,
        max_output_tokens=max(64, max_tokens),
    ).text


def qwen_answer(question: str, action: str, evidence_blocks: list[dict], chapter_hint: str,
                writeback_note: str = "", history: list[dict] | None = None,
                answer_budget: dict | None = None, figure_on_screen: bool = False,
                clarify: bool = False, intro: bool = False, visualize: bool = False) -> str:
    tone = {
        "ENCOURAGE": "The student is frustrated or overloaded. Be warm and brief; acknowledge effort first.",
        "MISCONCEPTION_PROBE": "Ask the diagnostic question from the evidence FIRST. Do not reveal the correction yet.",
        "SOCRATIC_Q": "Respond mainly with one guiding question; do not lecture.",
        "METACOGNITIVE_REFLECT": "The student just confirmed understanding. One short reflection question "
                                 "(e.g. 'explain it back in your own words') OR offer the next step. "
                                 "Do NOT re-explain anything already covered.",
        "REPRESENTATION_TRANSLATION": "Translate the idea into a different representation the student "
                                      "can picture — a scene, a figure, a drawing — not more words about "
                                      "the same definition.",
        "WHY_IT_MATTERS": "The student asked WHY this is worth learning, what it is for, or HOW "
                          "something connects to the topic (or said you did not answer their "
                          "question). ANSWER THAT EXACT QUESTION FIRST in one plain sentence. If "
                          "they asked how an example connects, state the connection explicitly "
                          "('that marble problem IS a quadratic equation because...'). If they "
                          "asked why learn it, give ONE concrete reason from a Class 10 student's "
                          "real life. Do NOT start a new problem, do NOT continue a previous "
                          "calculation, do NOT give a definition instead of the answer.",
    }.get(action, "Teach clearly and briefly at Class 10 level.")
    if intro:
        # Learning-start (rule 1c): the student is opening a brand-new topic. Give a
        # real welcoming overview that DELIVERS content, not a quiz or a one-liner.
        tone = ("The student is just starting this topic for the first time. Give a clear, "
                "friendly overview that actually teaches: say what it is and its ONE core idea "
                "in plain words, using the evidence, then end with a single inviting question to "
                "begin. Do NOT quiz them or assume prior knowledge of this topic.")
    hist_text = ""
    if history:
        hist_text = "RECENT CONVERSATION (do not repeat explanations already given here; build on them):\n" + \
            "\n".join(f"{h['role'].upper()}: {h['text']}" for h in history) + "\n\n"
    ev_text = "\n\n".join(
        f"EVIDENCE {i + 1}:\n{b['text'][:700]}" for i, b in enumerate(evidence_blocks) if b["text"]
    )[:6000]
    pacing = ""
    max_tokens = 400
    if answer_budget:
        max_words = int(answer_budget.get("max_words", 35))
        max_sentences = int(answer_budget.get("max_sentences", 2))
        micro = answer_budget.get("micro_check_type", "yes_no")
        must_end = answer_budget.get("must_end_with", "micro_check")
        # Token cap is generous enough to let the model FINISH its sentences (a
        # too-tight cap cuts mid-sentence and the fragment gets spoken — 2026-07-03
        # transcript: "...you divide 20 / 0." cut mid-division at the old 180 cap).
        # Real brevity is enforced by _truncate_to_spoken_budget below, which keeps
        # only whole sentences within the word budget.
        max_tokens = max(90, min(240, round(max_words * 3.5)))
        pacing = (
            "PACING CONTRACT FOR SPOKEN VOICE:\n"
            f"- Speak at most {max_words} words and {max_sentences} sentence(s).\n"
            "- Teach ONE complete atomic idea and actually DELIVER it in this reply.\n"
            "- Do NOT announce what you will do ('let's look at an example', 'let me "
            "explain'); just do it. Spend your words on the maths, not on preamble.\n"
            "- If you use an example, WORK IT OUT here: substitute the numbers and carry "
            "the calculation through to the final result (you may do the arithmetic "
            "yourself, e.g. D = (-4)^2 - 4*2*2 = 0). Do not stop at the formula, and "
            "never mention an example without giving it.\n"
            "- Use short, concrete sentences for a Class 10 student.\n"
            "- Do not repeat an explanation already present in RECENT CONVERSATION.\n"
        )
        if must_end == "micro_check" and action not in {"MISCONCEPTION_PROBE", "TRANSFER_PROBLEM", "QUIZ"}:
            micro_phrase = {
                "yes_no": "a short yes-or-no question",
                "own_words": "a short request to say it back in their own words",
                "answer": "a short question asking them to try the answer",
                "question": "one short guiding question",
                "try_step": "a short nudge to try the next step",
                "next_step": "a short check on what to do next",
            }.get(micro, "a short question")
            pacing += (
                f"- End with {micro_phrase}, but ONLY about what you actually explained "
                "in THIS reply. Never ask 'did you understand' about something you did not "
                "show. If you worked an example, ask them to state the result or try the "
                "next step.\n"
                "- Do NOT print any label like 'yes_no:' or 'check:'; just ask the question.\n"
                "- This is only for pacing, not for grading mastery.\n"
            )
        else:
            pacing += "- Do not add an extra pacing question after the required diagnostic/problem.\n"
        pacing += "\n"
    clarify_cue = ""
    if visualize:
        # Outranks the generic clarify cue: the student's problem is that they
        # cannot form a MENTAL IMAGE, so a re-worded definition is still a failure.
        clarify_cue = (
            "THE STUDENT SAID THEY CANNOT PICTURE / IMAGINE IT. Do NOT restate the "
            "definition in different words. Build ONE concrete scene from everyday "
            "life, step by step, that they can see in their head (e.g. 'Imagine you "
            "are standing 30 metres from a lamp post. Look up at its top. Your eyes, "
            "the top, and the base of the post make three corners of a right "
            "triangle.'). Name each part of the scene and say which part of the "
            "maths it is. If a figure is on the screen, walk them through that "
            "instead of inventing a new scene.\n"
        )
    elif clarify:
        clarify_cue = (
            "THE STUDENT SAID THEY DID NOT UNDERSTAND YOUR PREVIOUS REPLY (or that you "
            "are repeating yourself). Explain the SAME idea a DIFFERENT, simpler way: "
            "shorter sentences, plainer words, and a concrete number example. Do NOT "
            "repeat your earlier wording or ask the same question again.\n"
        )
    screen_cue = ""
    if figure_on_screen:
        screen_cue = (
            "A FIGURE FROM THE TEXTBOOK IS BEING SHOWN ON THE STUDENT'S SCREEN RIGHT NOW. "
            "Refer to it directly ('look at the figure on the screen', 'in the picture you "
            "can see…') and use it to make your point. Do NOT describe the picture in words "
            "as if they cannot see it — point them to it.\n"
        )
    # Hard style rules: the spoken budget is small, so filler is fatal. A greeting,
    # a self-introduction, or an apology eats the whole reply and teaches nothing
    # (transcript regression: "Namaste! I'm Wini…" / "My apologies! Let's focus…").
    style_cue = (
        "STYLE (strict):\n"
        "- Every reply must DELIVER maths content. Do NOT greet, do NOT introduce "
        "yourself, do NOT apologise or say sorry — no 'Namaste', 'I'm Wini', "
        "'My apologies', 'Sorry'. Even if the student is upset, respond by actually "
        "teaching, not by apologising.\n"
        "- Do NOT announce what you are about to do ('let's focus on…', 'let me "
        "explain…', 'let's try this'); just teach the thing itself.\n"
        "- NEVER re-ask a question you already asked in RECENT CONVERSATION, and do "
        "not repeat a sentence you already said; move the explanation forward.\n"
    )
    prompt = (
        f"You are Wini, a friendly Class 10 Maths tutor ({chapter_hint}).\n"
        f"Pedagogical action for this turn: {action}. {tone}\n"
        + (f"Context: {writeback_note}\n" if writeback_note else "")
        + style_cue
        + clarify_cue
        + screen_cue
        + pacing
        + "Use ONLY the evidence below — if it does not support a claim, say less. "
        "Never mention internal IDs, codes, or evidence numbers (no 'jemh104', no "
        "'EVIDENCE 2', no 'misconception::...'); speak naturally about the maths. "
        "Indian-English friendly.\n\n"
        f"{hist_text}{ev_text}\n\nSTUDENT: {question}\n\nWINI:"
    )
    text = qwen_chat(prompt, temperature=0.3, max_tokens=max_tokens)
    if answer_budget:
        text = _truncate_to_spoken_budget(
            text,
            int(answer_budget.get("max_words", 35)),
            int(answer_budget.get("max_sentences", 2)),
        )
    return text


def _budget_for_generation(answer_budget: dict | None, action: str) -> dict | None:
    """Resize the spoken budget to the ACTUAL pedagogical action.

    The pacing layer guesses a generic budget before the action is decided, so a
    WORKED_EXAMPLE would otherwise be capped at EXPLAIN's 35 words / 2 sentences —
    only enough to announce an example, not work it. We take the per-action word/
    sentence room from the pacing controller (single source of truth) while keeping
    the caller's micro-check decision (must_end_with reflects pending_check state).
    """
    if not answer_budget:
        return answer_budget
    try:
        from pacing.pacing_controller import ACTION_BUDGETS
        ab = ACTION_BUDGETS.get(action)
    except Exception:  # noqa: BLE001 — pacing not importable: keep caller's budget
        ab = None
    if not ab:
        return answer_budget
    out = dict(answer_budget)
    out["max_words"] = int(ab["max_words"])
    out["max_sentences"] = int(ab["max_sentences"])
    # adopt the action's check type (e.g. WORKED_EXAMPLE -> 'try_step', so the model
    # asks them to try the next step rather than 'did you understand'); but keep the
    # caller's must_end_with, which already encodes pending_check (no extra check).
    if out.get("must_end_with") == "micro_check":
        out["micro_check_type"] = ab.get("micro_check_type", out.get("micro_check_type"))
    return out


def _truncate_to_spoken_budget(text: str, max_words: int, max_sentences: int) -> str:
    """Enforce the spoken budget on Qwen's output for TTS.

    Keeps only COMPLETE sentences (this also drops a trailing fragment left by a
    token-capped generation, e.g. '...4 times 2' with no period). Then caps to
    max_sentences and to max_words, always keeping at least one sentence and
    preserving a trailing micro-check question if there is one.
    """
    import re as _re

    # A terminator only ends a sentence when followed by whitespace/end — a "." with
    # a digit right after is a DECIMAL POINT ("20 / 0.2"), not a boundary. The old
    # pattern split inside decimals, so the sentence cap cut replies mid-number and
    # re-joined "0." + "2 square metres" (2026-07-03 transcript, brick-wall reply).
    sentences = [s.strip() for s in _re.findall(r"[^.!?]*[.!?]+(?=\s|$)", text.strip()) if s.strip()]
    if not sentences:
        # no terminator at all (rare) — return the raw text, trimmed of any
        # obvious dangling open paren from a hard token cut.
        return text.strip().rstrip("(,-")
    kept: list[str] = []
    words = 0
    for s in sentences[:max_sentences]:
        w = len(s.split())
        if kept and words + w > max_words:
            break
        kept.append(s)
        words += w
    last = sentences[-1]
    if last.endswith("?") and not kept[-1].endswith("?"):
        # ensure the pacing micro-check survives the cap
        if words + len(last.split()) > max_words and len(kept) > 1:
            kept[-1] = last
        elif last not in kept:
            kept.append(last)
    return " ".join(kept)


def qwen_cohesion_check(evidence: list[dict], blocks_text: dict) -> list[str]:
    """A1.5 LLM half, local: when the bundle mixes >= 3 source types, ask Qwen
    whether any items contradict each other. Returns ids to drop (only
    chunk/figure items are droppable — diagnostics and bridges are protected).
    Any failure returns [] so the judge can never break retrieval."""
    types = {e["type"] for e in evidence}
    if len(types) < 3:
        return []
    droppable = [e for e in evidence if e["type"] in ("chunk", "figure")]
    if not droppable:
        return []
    listing = "\n".join(f"- id={e['id']}: {blocks_text.get(e['id'], '')[:200]}" for e in evidence
                        if blocks_text.get(e["id"]))
    prompt = (
        "These snippets will be combined into ONE maths tutoring reply. "
        "Do any DIRECTLY contradict each other (state incompatible facts)?\n"
        f"{listing}\n\n"
        'Respond with ONLY JSON: {"contradicting_ids": []} — list ids ONLY for true contradictions, '
        "not mere topic differences. Usually the list is empty."
    )
    try:
        import re as _re
        text = qwen_chat(prompt, temperature=0.0, max_tokens=120)
        m = _re.search(r"\[.*?\]", text, _re.DOTALL)
        if not m:
            return []
        flagged = set(json.loads(m.group(0)))
        return [e["id"] for e in droppable if e["id"] in flagged]
    except Exception:  # noqa: BLE001
        return []


def judge_answer(question: str, expected: str, student_answer: str) -> str:
    """Grade a diagnostic answer with the local Qwen model.

    Returns correct | partial | wrong | not_an_answer. Any failure (server
    down, unparseable output) degrades to not_an_answer so learner state is
    never moved by a broken grader.
    """
    prompt = (
        "You are grading a Class 10 maths check question.\n"
        f"QUESTION: {question}\n"
        f"EXPECTED ANSWER: {expected}\n"
        f"STUDENT REPLY: {student_answer}\n\n"
        'Classify the student reply. Respond with ONLY one JSON object like {"outcome": "correct"}.\n'
        "outcome must be one of: correct (matches expected), partial (right direction, "
        "incomplete or with an error), wrong (contradicts expected), not_an_answer "
        "(the reply does not attempt the question — e.g. a new question, topic change, or 'i dont know')."
    )
    try:
        text = qwen_chat(prompt, temperature=0.0, max_tokens=40)
        import re as _re
        m = _re.search(r'"outcome"\s*:\s*"(correct|partial|wrong|not_an_answer)"', text)
        if m:
            return m.group(1)
        m = _re.search(r"\b(correct|partial|wrong|not_an_answer)\b", text.lower())
        return m.group(1) if m else "not_an_answer"
    except Exception:  # noqa: BLE001
        return "not_an_answer"


# ---------------------------------------------------------------------------
# One turn
# ---------------------------------------------------------------------------


class TutorLoop:
    def __init__(self, state_path: Path = ROOT / "learner_state.json", want_answer: bool = True,
                 use_judge: bool = True):
        self.use_judge = use_judge
        # with_index=False: the loop ranks chunks with the local MiniLM index, not
        # the FAISS index (query.py standalone path) — and faiss is not installed
        # on the Jetson at all.
        self.chunks, self.concepts, self.graph, _ = load_store(STORE, with_index=False)
        self.concepts_by_id = {c["concept_id"]: c for c in self.concepts}
        self.chunks_by_id = {c["chunk_id"]: c for c in self.chunks}
        self.figure_misconceptions = {
            n: (a.get("disambiguates_misconceptions") or [])
            for n, a in self.graph.nodes(data=True) if a.get("image_path")
        }
        # Perception (Part 11 §7.1): inject ONE GeminiPerception as both the
        # classifier and resolver stubs so CognitiveAnalyzer.analyze() runs unchanged.
        # Its .embedder is a lazily-loaded MiniLM, so the HOPE + chunk-index wiring
        # below keeps working with zero edits. The MiniLM-heads runtime path was
        # retired at Stage 6 (2026-07-02) — a stale PERCEPTION_BACKEND=qwen_heads
        # env var is honored with a warning-free upgrade to gemini, never a crash.
        if PERCEPTION_BACKEND not in ("gemini", ""):
            print(f"[perception] PERCEPTION_BACKEND={PERCEPTION_BACKEND!r} is retired "
                  "(Stage 6, 2026-07-02) — using gemini. Heads remain eval-only.")
        from perception.gemini_perception import GeminiPerception
        # MiniLM device: on the Jetson, device_config.py (a Jetson-only module) pins
        # MiniLM to CPU (Part 9 — avoids a second CUDA context beside the other GPU
        # residents). On Windows/cloud the module is absent and the default applies.
        try:
            from device_config import get_config as _dev_cfg
            _minilm_device = _dev_cfg().minilm_device
        except ImportError:
            _minilm_device = None
        gp = GeminiPerception.load(device=_minilm_device)
        self.analyzer = CognitiveAnalyzer(classifier=gp, resolver=gp)
        # Persona / scripted replies for the non-learning intents (front door).
        self.persona = json.loads((ROOT / "persona.json").read_text(encoding="utf-8"))
        self.shadow = PolicyShadow.load()
        # HOPE detector shares the analyzer's MiniLM embedder (one model in VRAM)
        self.hope = HopeDetector.load(device=_minilm_device)
        self.hope.embedder = self.analyzer.classifier.embedder
        self.state = load_learner_state(state_path)
        # A fresh TutorLoop IS a fresh session: clear the transient lifecycle flags a
        # previous run left in the persisted state (a stale "ended"/leave count must
        # not hard-stop or fast-end the NEW session's first turns). pending_check,
        # context and all cognitive state deliberately survive (§4.3 resume contract).
        _sess = self.state.data.setdefault("session", {})
        _sess.pop("break_requested", None)
        _sess.pop("leave_requests", None)
        if _sess.get("status") in ("paused", "ended"):
            _sess["status"] = "active"
        self.chunk_emb = load_chunk_index(self.chunks, self.analyzer.classifier.embedder)
        self.want_answer = want_answer

    # which need mode serves which HOPE signal probe
    NEED_TO_HOPE = {"challenge": "CT", "transfer": "KT", "integrate": "KI"}
    HOPE_EV_TYPES = {"ct_probe": "CT", "transfer_target": "KT", "integration_target": "KI"}

    # T9 multimodal display channel: actions that are themselves visual, for which
    # an incidental figure-caption crop is worth SHOWING even when no pedagogy-gated
    # `figure` crop was selected (architecture section 9 "show, don't only tell").
    VISUAL_ACTIONS = {"REPRESENTATION_TRANSLATION", "VISUAL_ANALOGY"}

    @property
    def current_concept(self):
        return self.state.data.setdefault("session", {}).get("current_concept")

    def analyze_only(self, text: str) -> dict:
        """Analyze a student utterance without mutating learner state.

        Used by the voice pacing layer to triage mixed replies before the normal
        turn path decides which state channels may move.
        """
        return self.analyzer.analyze(text, current_concept=self.current_concept)

    def _build_display(self, evidence: list[dict], action: str) -> list[dict]:
        """T9 multimodal channel — pick at most ONE task-relevant figure crop to
        SHOW alongside speech (working-memory limit: one primary visual per turn).

        query.py already gates `figure`-type evidence to exactly the two
        pedagogical show-cases — a representation gap (need_evidence/integrate:
        ``reps_missing & supports_representation``) or disambiguating an active
        misconception (misconception_evidence corrective phase) — so any
        figure-type item is show-worthy. An *incidental* `figure_caption` chunk
        (a semantic match that happens to carry a crop) is shown only when the
        action is itself visual (REPRESENTATION_TRANSLATION / VISUAL_ANALOGY).
        Otherwise the turn stays audio-only and this returns [].

        Items are channel-agnostic: ``image_path`` stays store-relative so each
        DisplaySink (web /store route, Windows pane, Jetson /display_image)
        resolves it against the store root — never hard-coded.
        """
        primary = None    # pedagogy-gated `figure` crop (preferred)
        fallback = None   # incidental figure_caption chunk (visual actions only)
        for e in evidence:
            if not e.get("image_path"):
                continue
            if e["type"] == "figure":
                primary = e
                break
            if e["type"] == "chunk" and action in self.VISUAL_ACTIONS and fallback is None:
                fallback = e
        chosen = primary or fallback
        if not chosen:
            return []
        node = self.graph.nodes.get(chosen["id"], {})
        row = self.chunks_by_id.get(chosen["id"], {})
        alt = (chosen.get("alt_text") or node.get("alt_text")
               or (row.get("text") or "").split(":")[0].strip()[:120] or "figure")
        supports = (chosen.get("supports_representation") or node.get("supports_representation")
                    or row.get("representations") or [])
        return [{
            "image_path": chosen["image_path"],   # store-relative; sink resolves
            "alt_text": alt,
            "why": chosen.get("why", ""),
            "supports_representation": supports,
            "figure_id": chosen["id"],
        }]

    # ------------------------------------------------------------------
    # Front door: non-learning intents (Part 11 §4.3 / §7.3)
    # ------------------------------------------------------------------
    def _handle_nonlearning(self, route, text: str, answer_budget: dict | None = None) -> dict:
        """Handle a non-LEARNING intent WITHOUT moving cognitive state (§3/§7.3).

        Contract: never call analyze_and_apply; never arm/grade pending_check or
        pending_hope; PRESERVE an open pending_check so the next learning turn
        returns to the question; no retrieval; persona/scripted reply; still log to
        learning_log.jsonl with the resolved intent; same result-dict shape as
        turn() with display: [].
        """
        session = self.state.data.setdefault("session", {})
        intent = route.primary
        # SESSION_CONTROL sets lightweight session flags (autonomy support) while
        # preserving pending_check + all learner cognitive state (§4.3).
        if intent == "SESSION_CONTROL":
            self._apply_session_control(session, text)

        reply, reply_source = self._nonlearning_reply(route, text, session)

        # transient session memory only — no cognitive-state channel is touched
        ctx = session.setdefault("context", [])
        ctx.append({"role": "student", "text": text[:250]})
        if reply:
            ctx.append({"role": "wini", "text": reply[:250]})
        session["context"] = ctx[-8:]

        self._log_nonlearning(text, route, reply, reply_source)
        if self.state.path:
            self.state.save()

        pc = session.get("pending_check") or {}
        ph = session.get("pending_hope") or {}
        return {
            "action": intent, "action_reason": route.reason, "need": "none",
            "shadow": None,
            "concept": {"concept_id": route.concept_id,
                        "concept_confidence": route.concept_confidence,
                        "abstained": route.concept_id is None},
            "signals": [], "cognitive_update": {}, "n_evidence": 0, "bridge_ids": [],
            "writeback": None, "hope_update": None,
            "pending_check": pc.get("id"), "pending_hope": ph.get("signal"),
            "answer_budget": answer_budget, "pace": session.get("pace", {}),
            "display": [], "answer": reply,
            "intent": intent, "route_source": route.source,
            "answer_source": reply_source,
            "gen_backend": GEN_BACKEND if reply_source not in ("scripted", "farewell", "canned") else None,
            # runners speak the farewell, then stop taking turns (§4.3 hard stop)
            "session_ended": session.get("status") == "ended",
        }

    def _apply_session_control(self, session: dict, text: str) -> None:
        """A few lightweight flags, not a state machine (§4.3). pending_check and all
        learner cognitive state are left untouched; a later LEARNING turn resumes.

        End-of-session hard rule (gemini_tutor_issues.md #1/#5): every SESSION_CONTROL
        turn counts as a leave request. An explicit goodbye ends the session at once;
        a second leave request in a row ends it too — the tutor never gets a third
        chance to squeeze in "one small sum". The counter resets when a LEARNING turn
        actually resumes (see turn() resume block)."""
        import re as _re
        low = (text or "").lower()
        ended = _re.search(
            r"\b(bye|goodbye|good ?night|see you|that'?s all|i'?m done|we'?re done|"
            r"stop for (today|now)|end (the )?(session|lesson)|finish for|"
            r"i (want|have|need) to go(?! (over|through|back|on))|let me go|going now)\b", low)
        session["leave_requests"] = int(session.get("leave_requests", 0)) + 1
        session["status"] = "ended" if (ended or session["leave_requests"] >= 2) else "paused"
        session["break_requested"] = True

    def _nonlearning_reply(self, route, text: str, session: dict) -> tuple[str, str]:
        """Scripted for SAFETY/NONSENSE (fixed, human-reviewed, never model); persona
        for the rest (LLM via the shared seam when generating, else canned).

        Returns (reply, source) where source is "scripted" | "farewell" | "canned"
        | the generation backend name — so logs can prove where a reply came from
        (the 2026-07-03 transcript could not be attributed to qwen vs gemini)."""
        intent = route.primary
        spec = self.persona.get("intents", {}).get(intent, {})
        if "scripted" in spec:                    # SAFETY, NONSENSE
            return spec["scripted"], "scripted"
        # Session END is deterministic: a scripted warm farewell, never the LLM —
        # the model must get zero chance to append "just one quick question"
        # (gemini_tutor_issues.md #1: retention attempts after an explicit bye).
        if intent == "SESSION_CONTROL" and session.get("status") == "ended":
            fw = spec.get("farewell") or self._fill_persona(spec.get("canned", []), session)
            return fw, "farewell"
        canned = self._fill_persona(spec.get("canned", []), session)
        if not self.want_answer:
            return canned, "canned"
        try:
            prompt = self._persona_prompt(route, text, session, spec)
            reply = qwen_chat(prompt, temperature=0.5, max_tokens=90)
            reply = _truncate_to_spoken_budget(reply, 45, 2)
            return (reply, GEN_BACKEND) if reply else (canned, "canned")
        except Exception:  # noqa: BLE001 — generation down -> canned persona line
            return canned, "canned"

    def _persona_prompt(self, route, text: str, session: dict, spec: dict) -> str:
        p = self.persona
        concept = self._friendly_concept(session)
        instruction = spec.get("instruction", "Reply warmly and gently steer back to maths.")
        # SESSION_CONTROL (pause path — end is scripted upstream): the child asked to
        # stop, so the prompt must not invite a steer-back; every other persona intent
        # keeps the gentle redirect to the current topic.
        if route.primary == "SESSION_CONTROL":
            steer = ("Do NOT ask any question and do NOT mention a sum or problem to try. "
                     "Accept the pause warmly in one sentence.")
        else:
            steer = f"If you steer back to maths, the current topic is: {concept}."
        # Recent conversation so the reply can refer to what just happened ("I was
        # right!" -> confirm WHAT was right) instead of asking about it
        # (gemini_tutor_issues.md #2).
        ctx = session.get("context", [])[-6:]
        hist = ""
        if ctx:
            hist = "RECENT CONVERSATION (use it; never ask about something it already tells you):\n" + \
                "\n".join(f"{h['role'].upper()}: {h['text']}" for h in ctx) + "\n\n"
        return (
            f"{p.get('identity', '')}\n{p.get('style', '')}\n"
            f"Situation: {instruction}\n"
            f"{steer}\n\n"
            f"{hist}CHILD SAID: {text}\n\nWINI (one or two short spoken sentences):"
        )

    def _fill_persona(self, canned: list, session: dict) -> str:
        if not canned:
            return ""
        return str(canned[0]).replace("{concept}", self._friendly_concept(session))

    def _friendly_concept(self, session: dict) -> str:
        cid = session.get("current_concept")
        if cid:
            return self.concept_name(cid)
        return "our maths"

    def concept_name(self, cid: str | None) -> str:
        """Human-speakable name for a catalog concept id (never speak raw ids)."""
        if not cid:
            return "our maths"
        card = self.concepts_by_id.get(cid) or {}
        node = self.graph.nodes.get(cid, {})
        name = card.get("name") or card.get("display_name") or node.get("name")
        return str(name) if name else cid.split("__")[-1].replace("_", " ")

    # ------------------------------------------------------------------
    # Topic shift (deterministic; 2026-07-03 transcript fixes)
    # ------------------------------------------------------------------
    # MiniLM anchor-similarity thresholds for grounding a requested topic:
    # >= HI: switch directly (the request was explicit); >= LO: offer the match
    # and ask; below LO: the topic is off-catalog — say so honestly and offer
    # the nearest chapter topic instead of silently continuing the old one.
    # Calibrated 2026-07-03 on the shipped anchors: clean topic names score
    # 0.45-0.69 ("triangles" .507, "trigonometry" .548, "quadratic equations"
    # .686), vague-but-real "natural numbers" .313, noise ("pizza", "how are
    # you", "cricket score") <= .14.
    SHIFT_TAU_HI = 0.45
    SHIFT_TAU_LO = 0.25

    def _maybe_topic_shift(self, text: str, analysis: dict, session: dict,
                           answer_budget: dict | None) -> dict | None:
        """Detect and handle a topic-shift attempt the perception could not ground.

        Returns a completed turn result (confirm question / direct switch) or None
        to continue the normal pipeline. Never blocks the pipeline on failure —
        every fallible step degrades to `return None`.
        """
        from cognitive_classifier.cues import extract_topic_request, is_bare_topic

        concept = analysis["concept"]
        primary = concept["concept_id"]
        current = session.get("current_concept")
        span = extract_topic_request(text)
        # A bare label ("Natural numbers.") only counts when no GRADED question is
        # open — a bare phrase can be a legitimate answer to a diagnostic. An open
        # pace-only micro-check does NOT block it: micro checks never grade, and the
        # 2026-07-03 shift happened exactly while one was open; worst case the
        # confirm question below lets the student say no.
        graded_pending = bool(session.get("pending_check") or session.get("pending_hope"))
        bare = is_bare_topic(analysis["normalized_text"]) and not graded_pending
        if not span and not bare:
            return None
        # When perception confidently resolved a DIFFERENT catalog concept the
        # normal pipeline already shifts (current_concept := primary) — no friction.
        if primary and not concept["abstained"] and primary != current \
                and concept["concept_confidence"] >= 0.6:
            return None
        target_text = span or analysis["normalized_text"]
        cands = getattr(self.analyzer.classifier, "topic_candidates", None)
        cands = cands(target_text, 3) if callable(cands) else []
        if not cands:
            return None            # no resolver artifacts — never block the turn
        cid, name, sim = cands[0]
        if cid == current and sim >= self.SHIFT_TAU_LO:
            return None            # they asked for what we are already doing
        cur_name = self._friendly_concept(session)
        if span and sim >= self.SHIFT_TAU_HI:
            # explicit request, confidently grounded -> switch NOW (asking again
            # after "I asked about X" is exactly the friction that annoyed the kid)
            session["current_concept"] = cid
            session.pop("pending_check", None)
            session.pop("pending_hope", None)
            self._log_shift(text, "TOPIC_SHIFT", f"explicit request grounded to {cid} (sim {sim:.2f})")
            return self.turn(f"I want to learn about {name}", answer_budget=answer_budget,
                             _allow_shift=False)
        if sim >= self.SHIFT_TAU_LO:
            reply = (f"We're doing {cur_name} right now. Do you want to switch to "
                     f"{name}? Say yes or no.")
        else:
            asked = span or target_text
            reply = (f"Hmm, '{asked}' isn't one of our Class 10 topics. The closest I "
                     f"have is {name} — want to try that? Or say no to continue {cur_name}.")
        session["pending_shift"] = {"concept_id": cid, "name": name}
        return self._shift_reply(text, reply, "TOPIC_SHIFT_CONFIRM",
                                 f"shift request; top match {cid} (sim {sim:.2f})",
                                 session, answer_budget)

    def _consume_pending_shift(self, session: dict, text: str,
                               answer_budget: dict | None) -> dict | None:
        """Resolve last turn's 'switch to X?' offer. Bare yes -> execute the switch
        and open the new topic; bare no -> continue the current one; anything else
        -> cancel the offer and let the utterance take the normal path."""
        import re as _re
        low = (text or "").strip().lower()
        words = low.split()
        target = session.pop("pending_shift", None) or {}
        if not target.get("concept_id"):
            return None
        if _re.match(r"^(yes|yeah|ya|yep|ok(ay)?|sure|haan|ha)\b", low) and len(words) <= 3:
            session["current_concept"] = target["concept_id"]
            session.pop("pending_check", None)
            session.pop("pending_hope", None)
            self._log_shift(text, "TOPIC_SHIFT", f"confirmed switch to {target['concept_id']}")
            return self.turn(f"I want to learn about {target['name']}",
                             answer_budget=answer_budget, _allow_shift=False)
        if _re.match(r"^(no|nope|nah|not now)\b", low) and len(words) <= 3:
            reply = f"No problem — let's continue with {self._friendly_concept(session)}."
            return self._shift_reply(text, reply, "TOPIC_SHIFT_DECLINED",
                                     "shift offer declined; continuing current topic",
                                     session, answer_budget)
        return None    # neither: offer cancelled, normal pipeline handles the text

    def _shift_reply(self, text: str, reply: str, action: str, reason: str,
                     session: dict, answer_budget: dict | None) -> dict:
        """Deterministic (no-LLM) shift turn: context + log + save + result shape."""
        ctx = session.setdefault("context", [])
        ctx.append({"role": "student", "text": text[:250]})
        ctx.append({"role": "wini", "text": reply[:250]})
        session["context"] = ctx[-8:]
        self._log_shift(text, action, reason, reply)
        if self.state.path:
            self.state.save()
        pc = session.get("pending_check") or {}
        return {
            "action": action, "action_reason": reason, "need": "none", "shadow": None,
            "concept": {"concept_id": session.get("current_concept"),
                        "concept_confidence": 0.0, "abstained": True},
            "signals": [], "cognitive_update": {}, "n_evidence": 0, "bridge_ids": [],
            "writeback": None, "hope_update": None,
            "pending_check": pc.get("id"), "pending_hope": None,
            "answer_budget": answer_budget, "pace": session.get("pace", {}),
            "display": [], "session_ended": False, "answer": reply,
            "answer_source": "scripted", "gen_backend": None,
        }

    def _log_shift(self, text: str, action: str, reason: str, reply: str | None = None) -> None:
        log_row = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S"), "loop": "tutor_loop_v4",
            "question": text, "action": action, "action_reason": reason,
            "need": "none", "signals": [], "answer": reply,
        }
        with open(STORE / "learning_log.jsonl", "a", encoding="utf-8") as f:
            f.write(json.dumps(log_row, ensure_ascii=False) + "\n")

    def _log_safety(self, text: str, route) -> None:
        """Persist a safety_alert record + notify the supervising adult (§4.3 Q2).

        The alert is NOT cognitive state; it is a supervision record. In cloud this
        is a flagged Firestore write that fires a push/email/dashboard alert; on the
        quick-test rig it is an append-only log + an unmissable console signal.
        """
        record = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "learner_id": self.state.data.get("learner_id"),
            "utterance": text,
            "source": route.source,
            "handled": "scripted_reply+persisted_alert+supervisor_notify",
        }
        self.state.data.setdefault("safety_alerts", []).append(record)
        self.state.data.setdefault("session", {})["safety_alert"] = record
        try:
            with open(STORE / "safety_alerts.jsonl", "a", encoding="utf-8") as f:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
        except Exception:  # noqa: BLE001 — logging must never break the safety reply
            pass
        self._notify_supervisor(record)

    def _notify_supervisor(self, record: dict) -> None:
        """Active supervisor notification over the most reliable channel available.
        Cloud deployment overrides this with a Firestore write -> push/email/dashboard."""
        line = "=" * 64
        print(f"\n{line}\n  [!] SAFETY ALERT — a supervising adult must be notified now.\n"
              f"      utterance: {record.get('utterance')!r}\n{line}\n")

    def _log_nonlearning(self, text: str, route, reply: str, reply_source: str = "") -> None:
        log_row = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S"), "loop": "tutor_loop_v4",
            "question": text, "action": route.primary, "action_reason": route.reason,
            "need": "none", "intent": route.primary, "route_source": route.source,
            "safety_alert": bool(route.safety_alert),
            "concept": {"concept_id": route.concept_id,
                        "concept_confidence": route.concept_confidence,
                        "abstained": route.concept_id is None},
            "signals": [], "answer": reply,
            "answer_source": reply_source,
        }
        with open(STORE / "learning_log.jsonl", "a", encoding="utf-8") as f:
            f.write(json.dumps(log_row, ensure_ascii=False) + "\n")

    def turn(self, text: str, answer_budget: dict | None = None,
             precomputed_analysis: dict | None = None, _allow_shift: bool = True) -> dict:
        # -1. Pending topic-shift confirmation from the previous turn: a bare
        # yes/no answers the "switch to X?" offer deterministically (no model
        # call); anything longer falls through with the offer cancelled.
        session = self.state.data.setdefault("session", {})
        if session.get("pending_shift"):
            out = self._consume_pending_shift(session, text, answer_budget)
            if out is not None:
                return out

        # 0. Front door (Part 11 §7.2): deterministic gates FIRST (model-free,
        # regardless of backend), then the Gemini intent route when perception is
        # authoritative. Only LEARNING enters the state-moving pipeline (§3). The
        # Gemini call is memoized by normalized text, so route() and the later
        # analyze() share ONE network round-trip.
        route = _front_gate(text)
        if route is None:
            route = self.analyzer.classifier.route(text, self.state.data.setdefault("session", {}))
        if route is not None:
            if route.safety_alert:
                # The gate owns the safety decision; a model `safety` flag may only
                # ADD recall, never remove it (§4.2). Escalate to the scripted path.
                route.primary = "SAFETY"
                self._log_safety(text, route)
            if route.primary != "LEARNING":
                return self._handle_nonlearning(route, text, answer_budget)

        # 1-2. cognitive analysis + state update (Parts 1+2+3)
        if precomputed_analysis is None:
            analysis = self.analyzer.analyze_and_apply(text, self.state, current_concept=self.current_concept)
        else:
            from cognitive_analyzer.analyzer import apply_deltas

            analysis = precomputed_analysis
            analysis["new_global_state"] = apply_deltas(self.state, analysis["state_deltas"])
        concept = analysis["concept"]
        primary = concept["concept_id"]
        # 1a-shift. Topic-shift attempt the perception could NOT ground: a bare
        # topic label or an explicit "i asked about X / teach me X" whose resolved
        # concept is INHERIT or the (possibly negated) current concept. Runs BEFORE
        # current_concept is overwritten so the comparison is against the OLD topic.
        # 2026-07-03 regression: "Natural numbers." abstained -> silently continued
        # quadratics; "I asked about natural numbers, you are explaining me
        # quadratic equation" resolved to the negated quadratic concept.
        if _allow_shift:
            shifted = self._maybe_topic_shift(text, analysis, session, answer_budget)
            if shifted is not None:
                return shifted
        if primary:
            self.state.data.setdefault("session", {})["current_concept"] = primary

        # 1a. Is this reply an ATTEMPT at the question we asked, or a non-attempt
        # (acknowledgment, "I don't understand", a fresh request, a counter-
        # question)? Computed once and reused by the diagnostic grader (1b),
        # the HOPE scorer (1c) and the pedagogy rules so a confusion plea is
        # never written back as a "wrong" diagnostic answer (learning_log
        # regression: "i can not understand" graded wrong → mastery dropped).
        from cognitive_classifier.cues import (
            is_pure_ack, is_question, is_clarification_request, is_answer_attempt,
            is_visualization_request, is_purpose_question, is_learning_request,
        )
        _sig = set(analysis["signals"])
        _norm = analysis["normalized_text"]
        clarification = is_clarification_request(text) or "simplification_request" in _sig
        # A visualization plea ("I cannot imagine this") is a representation gap:
        # the explicit deterministic cue always counts; a generic confusion plea
        # counts too when perception saw a representation signal on the same turn.
        # Plain representation signals without distress stay at rule 6 priority.
        wants_visual = is_visualization_request(text) or (
            clarification and bool(_sig & {"request_representation", "representation_shift"}))
        # A purpose/connection question ("why do I have to learn this", "how is
        # this related to X", "you didn't answer my question") must be ANSWERED,
        # not met with a probe/problem — rule 1w.
        wants_why = is_purpose_question(text)
        # §7.4: Gemini's answer_attempt is the primary signal when perception is
        # authoritative, with the classifier signal + surface cue as fallback. This
        # attacks the logged regression where "i can not understand" was graded wrong.
        answer_try = bool(route and route.answer_attempt) \
            or ("answer_attempt" in _sig) or is_answer_attempt(text)
        wants_hint = ("hint_requested" in analysis["state_deltas"]["concept_flags"]
                      or "request_hint" in _sig)
        fresh_request = wants_hint or bool(_sig & {
            "request_representation", "representation_shift",
            "simplification_request", "example_request", "topic_shift"})
        # a non-attempt carries no answer cue AND looks like an ack / confusion plea /
        # bare question / fresh request rather than a try at the pending question
        non_attempt = (not answer_try) and (
            is_pure_ack(_norm) or clarification or is_question(text) or fresh_request)

        # 1b. pending diagnostic from the previous turn (closed loop, section 8):
        # a hint request escalates the hint chain (never past it, rule 10); any
        # other reply is graded by Qwen and written back via the evidence APIs.
        session = self.state.data.setdefault("session", {})
        # A LEARNING turn resumes a session paused/ended by SESSION_CONTROL. The
        # preserved pending_check is graded normally below, so the question the child
        # left open is picked back up automatically (§4.3 resume contract).
        if session.get("status") in ("paused", "ended") or session.get("break_requested"):
            session["status"] = "active"
            session.pop("break_requested", None)
            session.pop("leave_requests", None)  # the child chose to come back
        pending = session.get("pending_check")
        writeback = None
        if pending:
            wants_hint = "hint_requested" in analysis["state_deltas"]["concept_flags"] \
                or "request_hint" in analysis["signals"]
            chain = pending.get("hint_chain") or []
            if wants_hint and chain:
                k = self.state.record_hint_request(pending["concept_id"], pending["id"])
                if k <= len(chain):
                    hint = chain[k - 1]
                    hint_text = hint.get("text") if isinstance(hint, dict) else str(hint)
                    self._log(text, f"HINT_LEVEL_{k}", "rule 10: fade one hint level, never the answer",
                              "hint", None, analysis, {"evidence": [ev(pending["id"], "hint",
                                                                       f"hint level {k} of pending diagnostic",
                                                                       text=hint_text)]})
                    if self.state.path:
                        self.state.save()
                    return {"action": f"HINT_LEVEL_{k}", "action_reason": "hint chain level served",
                            "need": "hint", "shadow": None, "concept": concept,
                            "signals": analysis["signals"], "cognitive_update": analysis["cognitive_update"],
                            "n_evidence": 1, "bridge_ids": [], "display": [], "answer": hint_text}
                # chain exhausted: fall through — rule 10 says switch action, don't leak
            # Only grade a reply that actually ATTEMPTS the question. A non-attempt
            # (ack, "I don't understand", a fresh request, a counter-question) must
            # never move mastery or force a misconception active — the weak local
            # judge otherwise returns "wrong" for plain confusion (see 1a).
            if non_attempt:
                outcome = "not_an_answer"
            else:
                outcome = judge_answer(pending["question"], pending["expected_answer"], text) \
                    if self.want_answer else "not_an_answer"
            if outcome in ("correct", "partial", "wrong"):
                hints_used = (self.state.concept_states.get(pending["concept_id"]) or {}) \
                    .get("hints_used_current", 0)
                if pending["kind"] == "bridge":
                    writeback = self.state.apply_bridge_result(pending["id"], outcome)
                else:
                    writeback = self.state.apply_probe_result(
                        pending["id"], outcome, concept_id=pending["concept_id"], hints_used=hints_used)
                writeback["graded_reply"] = text
            session.pop("pending_check", None)

        # 1c. pending HOPE probe from the previous turn (Part 4 wired live): if
        # the tutor served a CT/KT/KI probe last turn and the student attempted
        # an answer, score it 0-3 with the HOPE detector and fold into the
        # rolling KI/KT/CT averages (consumed by query.py ranking w7).
        hope_update = None
        pending_hope = session.get("pending_hope")
        if pending_hope:
            # only score a substantive attempt at the probe — a non-attempt
            # (ack / confusion plea / fresh request / counter-question) must not
            # be scored 0 and drag the rolling HOPE average down (see 1a)
            attempted = (not non_attempt) and len(text.split()) >= 4
            if attempted:
                r = self.hope.score(pending_hope["signal"], pending_hope["prompt"],
                                    text, pending_hope.get("rubric_anchor", ""))
                rolling = self.state.update_hope(pending_hope["signal"], r["score"])
                hope_update = {"signal": pending_hope["signal"], "label": r["label"],
                               "score": r["score"], "rolling": rolling}
            session.pop("pending_hope", None)

        # 2b. acknowledgment handling + representation write-back (v3): a
        # confirmed REPRESENTATION_TRANSLATION marks the served representations
        # as known for the session concept (architecture section 9 coverage)
        from cognitive_classifier.cues import is_pure_ack
        acknowledged = is_pure_ack(analysis["normalized_text"])
        if acknowledged and primary and session.get("last_action") == "REPRESENTATION_TRANSLATION":
            cs = self.state.concept_states.setdefault(primary, {})
            known = cs.setdefault("representations_known", [])
            for rep in session.get("last_repr_targets", []):
                if rep and rep not in known:
                    known.append(rep)

        # 3. pedagogy: rules decide, shadow suggests (logged only)
        # A "learning start" is a not-yet-mastered concept the student is asking to
        # learn (curiosity or a bare question), with no distress, no pending check, and
        # no answer attempt — introduce it rather than quiz it (rule 1c). Gate on
        # MASTERY, not is_known: apply_deltas creates a concept-state row on the first
        # turn, so is_known() is already True by here even for a brand-new topic;
        # mastery stays at COLD_START until graded evidence moves it.
        # An EXPLICIT "I want to learn / teach me" request always teaches (never a
        # cold quiz), even when the concept carries prior mastery — the 2026-07-03
        # transcript opened with "I want to learn about the quadratic equation" and
        # got QUIZ because perception's signals were empty and mastery was warm.
        # The welcoming-intro TONE stays reserved for genuinely new topics.
        explicit_learn = is_learning_request(text)
        learning_start = (
            bool(primary)
            and (self.state.mastery(primary) <= COLD_START_MASTERY or explicit_learn)
            and not answer_try and not acknowledged and not pending
            and (("curiosity" in _sig) or ("question" in _sig) or is_question(text)
                 or explicit_learn or bool(_sig & {"example_request", "learning_goal"}))
            and analysis["cognitive_update"].get("frustration_risk", 0.0) < 0.6
        )
        action, need, why = rules_decide(
            analysis["cognitive_update"], analysis["signals"],
            analysis["state_deltas"]["concept_flags"], concept["abstained"],
            acknowledged=acknowledged,
            clarification=(clarification and not answer_try),
            learning_start=learning_start,
            visual=(wants_visual and not answer_try),
            purpose=(wants_why and not answer_try),
        )
        intro = (learning_start and action == "EXPLAIN"
                 and bool(primary) and self.state.mastery(primary) <= COLD_START_MASTERY)
        shadow = self.shadow.suggest(analysis, self.analyzer.classifier)

        # 4. retrieval over the local index, reusing query.py machinery
        concept_hits = [{"concept_id": primary, "score": concept["concept_confidence"]}] if primary else []
        concept_hits += [{"concept_id": c, "score": 0.3} for c in concept.get("secondary_concepts", [])]
        concept_ids = [h["concept_id"] for h in concept_hits]
        band, band_reason = resolve_band(concept_hits, self.state, None)
        snapshot = Snapshot(self.state, primary, self.concepts_by_id.get(primary), self.graph, band)

        evidence: list[dict] = []
        evidence += bridge_evidence(self.graph, self.chunks_by_id, snapshot, concept_ids,
                                    force=(need == "bridge"))
        evidence += misconception_evidence(self.graph, snapshot)
        evidence += need_evidence(self.graph, self.concepts_by_id, snapshot, need, None)

        # candidate probe: the analyzer suspects a misconception but none is
        # active in state yet — serve the concept's first untracked
        # misconception diagnostic (probe before correcting, rule 8)
        if action == "MISCONCEPTION_PROBE" and primary and primary in self.graph \
                and not any(e["type"] == "misconception" for e in evidence):
            # concept-card `misconceptions` are free text; the nodes hang off the
            # concept via has_misconception edges
            for _, mid, d in self.graph.out_edges(primary, data=True):
                if d.get("relation") != "has_misconception":
                    continue
                if self.state.misconception_status(mid) not in ("untracked", "weakening"):
                    continue
                a = self.graph.nodes[mid]
                if a.get("diagnostic_question"):
                    evidence.insert(0, ev(mid, "misconception",
                                          "suspected via analyzer; diagnostic served (probe-first)",
                                          diagnostic_question=a.get("diagnostic_question"),
                                          hint_chain=a.get("hint_chain")))
                    break

        # arm the pending check for the NEXT turn: first diagnostic served wins
        # (bridges precede misconceptions in evidence order, matching section 6.8).
        # ONLY the two mastery-grading diagnostics may arm it — a `ct_probe` also
        # carries a `question`, but CT/KT/KI probes are scored by the HOPE path
        # (pending_hope) and must NOT be graded as misconceptions: doing so wrote
        # a bogus `ct_probe::...` entry into misconception_states and moved mastery
        # (learning_log regression — a Socratic turn tanked quadratic_zero_geometry).
        for e in evidence:
            if e["type"] not in ("bridge_diagnostic", "misconception"):
                continue
            q = e.get("question") or e.get("diagnostic_question")
            if not q:
                continue
            node = self.graph.nodes.get(e["id"], {})
            session["pending_check"] = {
                "kind": "bridge" if e["type"] == "bridge_diagnostic" else "misconception",
                "id": e["id"], "concept_id": primary or e.get("target_concept"),
                "question": q, "expected_answer": node.get("expected_answer", ""),
                "hint_chain": e.get("hint_chain") or node.get("hint_chain"),
            }
            break

        candidates_idx = [i for i, r in enumerate(self.chunks)
                          if any(c in (r.get("concept_ids") or []) for c in concept_ids)] \
            or list(range(len(self.chunks)))
        q_emb = self.analyzer.classifier.embed([analysis["normalized_text"]])
        sims = (q_emb @ self.chunk_emb[candidates_idx].T)[0]
        order = np.argsort(-sims)[:24]
        ranked = [dict(self.chunks[candidates_idx[j]], score=float(max(sims[j], 0.0))) for j in order]
        top, trace = snapshot_rerank(ranked, snapshot, need, 6, self.figure_misconceptions)
        for r in top:
            evidence.append(ev(r["chunk_id"], "chunk",
                               f"local semantic+pedagogic match (role={r.get('pedagogical_role')})",
                               image_path=r.get("image_path") if r.get("kind") == "figure_caption" else None))
        cohesion_log = cohesion_filter(self.graph, evidence, self.chunks, concept_ids,
                                       band[2], None, use_judge=False)
        # v3: local Qwen contradiction judge (cost-gated to >= 3 evidence types)
        if self.use_judge and self.want_answer:
            blocks_text = {}
            for e in evidence:
                row = self.chunks_by_id.get(e["id"])
                blocks_text[e["id"]] = (row or {}).get("text") or e.get("text") \
                    or e.get("question") or e.get("why_wrong") or ""
            dropped = qwen_cohesion_check(evidence, blocks_text)
            if dropped:
                evidence = [e for e in evidence if e["id"] not in dropped]
                cohesion_log = (cohesion_log or []) + [f"qwen_judge dropped: {dropped}"]

        manifest = {
            "evidence": evidence,
            "bridge_ids": [e["id"] for e in evidence if e["type"].startswith("bridge")],
            "schema_ids": [e["id"] for e in evidence if e["type"] == "problem_schema"],
            "ranking_trace": trace, "cohesion_log": cohesion_log,
            "snapshot": snapshot.summary(), "band_reason": band_reason,
        }

        # 4b. T9 display channel: pick the one figure crop (if any) to SHOW this
        # turn. Computed before generation so the prompt can reference it on screen.
        display = self._build_display(evidence, action)

        # 5. response from manifest only (Qwen, local)
        answer = None
        if self.want_answer:
            blocks = []
            for e in evidence:
                row = self.chunks_by_id.get(e["id"])
                txt = (row or {}).get("text") or e.get("text") or e.get("question") \
                    or e.get("why_wrong") or e.get("prompt") or e.get("note") or ""
                blocks.append({"source_path": e["id"], "text": txt})
            chapter_hint = "Class 10 Mathematics"
            if primary:
                doc = self.graph.nodes.get(primary, {}).get("chapter_doc")
                chap = self.graph.nodes.get(f"chapter::{doc}", {}) if doc else {}
                if chap.get("name"):
                    chapter_hint += f", Chapter: {chap['name']}"
            note = ""
            if writeback:
                note = (f"The student just answered the previous check question: outcome was "
                        f"'{writeback['outcome']}'. "
                        + ("Acknowledge it and continue." if writeback["outcome"] == "correct"
                           else "Gently correct using the evidence; do not scold."))
            # The pacing layer computed answer_budget BEFORE the action was known
            # (generic EXPLAIN). Now that the action is decided, give the generator
            # the action-appropriate word/sentence room — e.g. a WORKED_EXAMPLE
            # needs space to actually work the example, not just announce it.
            gen_budget = _budget_for_generation(answer_budget, action)
            answer = qwen_answer(text, action, blocks, chapter_hint, writeback_note=note,
                                 history=session.get("context", [])[-6:],
                                 answer_budget=gen_budget, figure_on_screen=bool(display),
                                 clarify=(clarification and not answer_try), intro=intro,
                                 visualize=(wants_visual and not answer_try))

        # 6. session memory (section 12.3 transient context) + bookkeeping for
        # the next turn's acknowledgment handling
        ctx = session.setdefault("context", [])
        ctx.append({"role": "student", "text": text[:250]})
        if answer:
            ctx.append({"role": "wini", "text": answer[:250]})
        session["context"] = ctx[-8:]
        session["last_action"] = action
        session["last_repr_targets"] = sorted({
            rep for e in evidence
            for rep in (e.get("supports_representation") or [])
        }) if action == "REPRESENTATION_TRANSLATION" else []

        # arm a HOPE probe for next-turn scoring if this turn served a CT/KT/KI
        # probe (the student answers Qwen's posed question, so for transfer/
        # integration the generated answer text is the prompt; ct_probe carries
        # its own stored question + expected_insight rubric)
        hope_signal = self.NEED_TO_HOPE.get(need)
        probe_ev = next((e for e in evidence if self.HOPE_EV_TYPES.get(e["type"]) == hope_signal), None) \
            if hope_signal else None
        if probe_ev:
            session["pending_hope"] = {
                "signal": hope_signal,
                "id": probe_ev["id"],
                "prompt": probe_ev.get("question") or (answer or "")[:500],
                "rubric_anchor": probe_ev.get("expected_insight") or probe_ev.get("note") or "",
            }

        # 7. log + persist (section 12.2; rules + shadow logged side by side)
        # (The Stage-1 perception shadow hook was removed with the heads at Stage 6 —
        # Gemini IS the authoritative perception now; _log keeps the field for old rows.)
        self._log(text, action, why, need, shadow, analysis, manifest, writeback, hope_update)
        self.state.mark_served([e["id"] for e in evidence])
        if self.state.path:
            self.state.save()

        return {"action": action, "action_reason": why, "need": need, "shadow": shadow,
                "concept": concept, "signals": analysis["signals"],
                "cognitive_update": analysis["cognitive_update"],
                "n_evidence": len(evidence), "bridge_ids": manifest["bridge_ids"],
                "writeback": writeback, "hope_update": hope_update,
                "pending_check": session.get("pending_check", {}).get("id"),
                "pending_hope": session.get("pending_hope", {}).get("signal"),
                "answer_budget": answer_budget,
                "pace": session.get("pace", {}),
                "display": display,
                "session_ended": False,
                "gen_backend": GEN_BACKEND if self.want_answer else None,
                "answer": answer}

    def _log(self, text, action, why, need, shadow, analysis, manifest, writeback=None,
             hope_update=None, perception_shadow=None) -> None:
        concept = analysis["concept"]
        log_row = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S"), "loop": "tutor_loop_v4",
            "question": text, "action": action, "action_reason": why, "need": need,
            "shadow_suggestion": shadow, "signals": analysis["signals"],
            "cognitive_update": analysis["cognitive_update"],
            "concept": {k: concept[k] for k in ("concept_id", "concept_confidence", "abstained")},
            "writeback": writeback, "hope_update": hope_update,
            # which LLM produced this turn's answer — qwen (local llama.cpp) or
            # gemini (Vertex); None when generation was skipped (--no-answer)
            "gen_backend": GEN_BACKEND if self.want_answer else None,
            "manifest": manifest,
        }
        if perception_shadow is not None:
            log_row["perception_shadow"] = perception_shadow
        with open(STORE / "learning_log.jsonl", "a", encoding="utf-8") as f:
            f.write(json.dumps(log_row, ensure_ascii=False) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--once", default=None, help="run a single turn and print JSON")
    ap.add_argument("--state", default=str(ROOT / "learner_state.json"))
    ap.add_argument("--no-answer", action="store_true", help="skip Qwen generation")
    ap.add_argument("--no-judge", action="store_true", help="disable the Qwen cohesion judge")
    args = ap.parse_args()

    loop = TutorLoop(state_path=Path(args.state), want_answer=not args.no_answer,
                     use_judge=not args.no_judge)
    if args.once:
        out = loop.turn(args.once)
        print(json.dumps(out, indent=2, ensure_ascii=False))
        return
    print("Wini tutor loop (local MiniLM + Qwen). Ctrl+C or 'quit' to exit.")
    while True:
        try:
            text = input("\nyou> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if not text or text.lower() in {"quit", "exit"}:
            break
        out = loop.turn(text)
        shadow_action = (out.get("shadow") or {}).get("action")
        print(f"[{out['action']} | {out['concept']['concept_id']} | {out['n_evidence']} evidence"
              f" | shadow: {shadow_action}]")
        if out["answer"]:
            print(f"wini> {out['answer']}")
        if out.get("session_ended"):
            print("(session ended by the student — hard stop)")
            break


if __name__ == "__main__":
    main()
