"""Turn lifecycle contracts and coordination foundations."""

from .contracts import (
    DeviceCapabilities,
    FailureSignal,
    FailureSeverity,
    ModuleOutcome,
    ProvisionalOutput,
    RealizationReceipt,
    RealizationStatus,
    StateChange,
    StateOperation,
    StateScope,
    TurnBudgets,
    TurnCommit,
    TurnContext,
    TurnInput,
    TurnResult,
    deep_thaw,
)
from .coordinator import (
    LOGICAL_TURN_PHASES,
    CoordinatedTurn,
    LegacyExecution,
    RecoveryAction,
    RecoveryCapability,
    RecoveryPolicy,
    TurnCoordinator,
    TurnPhase,
)
from .supervisor import RuntimeHealth, RuntimeHealthSnapshot, RuntimeSupervisor
from .compatibility import TutorLoopCompatibilityFacade

__all__ = [
    "DeviceCapabilities",
    "FailureSignal",
    "FailureSeverity",
    "ModuleOutcome",
    "ProvisionalOutput",
    "RealizationReceipt",
    "RealizationStatus",
    "StateChange",
    "StateOperation",
    "StateScope",
    "TurnBudgets",
    "TurnCommit",
    "TurnContext",
    "TurnInput",
    "TurnResult",
    "deep_thaw",
    "LOGICAL_TURN_PHASES",
    "CoordinatedTurn",
    "LegacyExecution",
    "RecoveryAction",
    "RecoveryCapability",
    "RecoveryPolicy",
    "TurnCoordinator",
    "TurnPhase",
    "RuntimeHealth",
    "RuntimeHealthSnapshot",
    "RuntimeSupervisor",
    "TutorLoopCompatibilityFacade",
]
