"""Build + calibrate + evaluate the concept resolver (plan Part 2).

Data: dataset/exemplar_dataset_10000_curated.json `concept_id` column —
98 explicit store concepts (~6,088 rows) + INHERIT_CURRENT_CONCEPT (~3,912
rows) as the abstain class. Splits: REUSES the frozen Part 1 splits.json
(models/exemplar_classifier/) so test rows are shared across all models
trained on this dataset. Augmented Part 1 rows are NOT used here (all carry
INHERIT and would skew the abstain prior).

Candidates, all calibrated on validation (joint alpha/k/tau grid for blend,
tau for logreg), selected by combined = (top1_explicit + abstain_F1) / 2:
  blend   alpha * exemplar-kNN + (1-alpha) * concept-card anchor similarity
  logreg  multinomial logistic head over seen concepts + ABSTAIN class

Metrics reported on the held-out test split:
  - top-1 / top-3 accuracy on explicit-concept rows (pre-abstain ranking)
  - top-1 after the abstain rule (an abstain on an explicit row = error)
  - abstain precision / recall / F1 on INHERIT rows

Usage:  python -m concept_resolver.build_resolver
"""

from __future__ import annotations

import json
import time
from pathlib import Path

import numpy as np

from cognitive_classifier.classifier import MODEL_NAME, score_labels_knn
from .resolver import DEFAULT_MODEL_DIR

ROOT = Path(__file__).resolve().parent.parent
DATASET = ROOT / "dataset" / "exemplar_dataset_10000_curated.json"
CONCEPTS = ROOT / "rag_store" / "concepts.json"
SPLITS = ROOT / "models" / "exemplar_classifier" / "splits.json"
INHERIT = "INHERIT_CURRENT_CONCEPT"

ALPHA_GRID = np.arange(0.0, 1.01, 0.1)
K_GRID = (8, 16, 32)
TAU_GRID = np.arange(0.02, 0.82, 0.02)


def anchor_text(card: dict) -> str:
    parts = [card["name"]]
    if card.get("aliases"):
        parts.append("Also called: " + ", ".join(card["aliases"]))
    if card.get("vocabulary"):
        parts.append("Key terms: " + ", ".join(card["vocabulary"]))
    if card.get("summary"):
        parts.append(card["summary"])
    return ". ".join(parts)


def evaluate(scores: np.ndarray, truth_idx: np.ndarray, is_inherit: np.ndarray, tau: float) -> dict:
    """truth_idx = concept index, -1 for INHERIT rows."""
    best = scores.argmax(axis=1)
    conf = scores.max(axis=1)
    abstain = conf < tau
    explicit = ~is_inherit

    top1_rank = (best[explicit] == truth_idx[explicit]).mean()
    order3 = np.argsort(-scores[explicit], axis=1)[:, :3]
    top3_rank = (order3 == truth_idx[explicit, None]).any(axis=1).mean()
    top1_final = ((best == truth_idx) & ~abstain)[explicit].mean()

    tp = float((abstain & is_inherit).sum())
    precision = tp / max(abstain.sum(), 1)
    recall = tp / max(is_inherit.sum(), 1)
    f1 = 2 * precision * recall / max(precision + recall, 1e-9)
    return {
        "top1_rank": float(top1_rank), "top3_rank": float(top3_rank),
        "top1_final": float(top1_final),
        "abstain_precision": float(precision), "abstain_recall": float(recall),
        "abstain_f1": float(f1),
        "combined": float((top1_final + f1) / 2),
    }


def main() -> None:
    t0 = time.time()
    rows = json.loads(DATASET.read_text(encoding="utf-8"))
    cards = json.loads(CONCEPTS.read_text(encoding="utf-8"))
    cards = cards if isinstance(cards, list) else cards["concepts"]
    concept_ids = [c["concept_id"] for c in cards]
    concept_names = [c["name"] for c in cards]
    cindex = {cid: i for i, cid in enumerate(concept_ids)}

    splits = json.loads(SPLITS.read_text(encoding="utf-8"))["row_ids"]
    train, val, test = list(splits["train"]), list(splits["val"]), list(splits["test"])

    # concept-gap rows (generated by the local Qwen server) carry their own
    # split field; the frozen Part 1 splits.json is never modified
    gap_path = ROOT / "dataset" / "concept_gap_utterances.json"
    gap_concept_ids: set[str] = set()
    if gap_path.exists():
        gap_rows = json.loads(gap_path.read_text(encoding="utf-8"))
        base = len(rows)
        for i, g in enumerate(gap_rows):
            {"train": train, "val": val, "test": test}[g["split"]].append(base + i)
            gap_concept_ids.add(g["concept_id"])
        rows = rows + gap_rows
        print(f"merged {len(gap_rows)} gap rows for {len(gap_concept_ids)} previously uncovered concepts")

    truth_idx = np.array([cindex.get(r["concept_id"], -1) for r in rows])
    is_inherit = np.array([r["concept_id"] == INHERIT for r in rows])
    bad = (~is_inherit) & (truth_idx < 0)
    if bad.any():
        raise SystemExit(f"{bad.sum()} rows have concept_ids not in the store")

    from sentence_transformers import SentenceTransformer

    embedder = SentenceTransformer(MODEL_NAME)
    print("embedding anchors + utterances…")
    anchor_emb = np.asarray(
        embedder.encode([anchor_text(c) for c in cards], normalize_embeddings=True, show_progress_bar=False),
        dtype=np.float32,
    )
    utt_emb = np.asarray(
        embedder.encode([r["student_utterance"] for r in rows], batch_size=256,
                        normalize_embeddings=True, show_progress_bar=True),
        dtype=np.float32,
    )

    bank_rows = [i for i in train if not is_inherit[i]]  # explicit-concept exemplars only
    bank_emb = utt_emb[bank_rows]
    bank_concepts = np.zeros((len(bank_rows), len(concept_ids)), dtype=np.float32)
    for r, i in enumerate(bank_rows):
        bank_concepts[r, truth_idx[i]] = 1.0
    seen = bank_concepts.sum(axis=0)
    print(f"bank: {len(bank_rows)} explicit rows covering {(seen > 0).sum()}/{len(concept_ids)} concepts")

    val_idx, test_idx = np.array(val), np.array(test)
    cards_val = np.clip(utt_emb[val_idx] @ anchor_emb.T, 0.0, None)
    cards_test = np.clip(utt_emb[test_idx] @ anchor_emb.T, 0.0, None)

    # --- candidate 1: blend (joint alpha/k/tau grid on val) ---------------------
    best_blend = None
    for k in K_GRID:
        knn_val = score_labels_knn(utt_emb[val_idx], bank_emb, bank_concepts, k)
        for alpha in ALPHA_GRID:
            scores = alpha * knn_val + (1 - alpha) * cards_val
            for tau in TAU_GRID:
                m = evaluate(scores, truth_idx[val_idx], is_inherit[val_idx], tau)
                if best_blend is None or m["combined"] > best_blend["m"]["combined"]:
                    best_blend = {"k": k, "alpha": round(float(alpha), 2), "tau": round(float(tau), 2), "m": m}
    print(f"blend best: {({kk: best_blend[kk] for kk in ('k', 'alpha', 'tau')})} "
          f"val combined={best_blend['m']['combined']:.4f}")

    # --- candidate 2: multinomial logreg with ABSTAIN class --------------------
    from sklearn.linear_model import LogisticRegression

    train_arr = np.array(train)
    y = np.where(is_inherit[train_arr], len(concept_ids), truth_idx[train_arr])
    logreg = LogisticRegression(max_iter=1000, C=4.0)
    logreg.fit(utt_emb[train_arr], y)

    def lr_scores(emb: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        proba = logreg.predict_proba(emb)
        out = np.zeros((emb.shape[0], len(concept_ids)), dtype=np.float32)
        abstain_p = np.zeros(emb.shape[0], dtype=np.float32)
        for col, cls in enumerate(logreg.classes_):
            if cls == len(concept_ids):
                abstain_p = proba[:, col]
            else:
                out[:, cls] = proba[:, col]
        return out, abstain_p

    lr_val, lr_val_abst = lr_scores(utt_emb[val_idx])
    best_lr = None
    for tau in TAU_GRID:
        # abstain when the ABSTAIN class outscores concepts OR confidence < tau
        conf = lr_val.max(axis=1)
        eff = lr_val.copy()
        eff[(lr_val_abst > conf) | (conf < tau)] = 0.0  # zero scores force abstain via tau rule
        m = evaluate(eff, truth_idx[val_idx], is_inherit[val_idx], max(tau, 1e-6))
        if best_lr is None or m["combined"] > best_lr["m"]["combined"]:
            best_lr = {"tau": round(float(tau), 2), "m": m}
    print(f"logreg best: tau={best_lr['tau']} val combined={best_lr['m']['combined']:.4f}")

    # --- selection + test evaluation --------------------------------------------
    ship_blend = best_blend["m"]["combined"] >= best_lr["m"]["combined"]
    if ship_blend:
        k, alpha, tau = best_blend["k"], best_blend["alpha"], best_blend["tau"]
        knn_test = score_labels_knn(utt_emb[test_idx], bank_emb, bank_concepts, k)
        test_scores = alpha * knn_test + (1 - alpha) * cards_test
        test_m = evaluate(test_scores, truth_idx[test_idx], is_inherit[test_idx], tau)
        method = "blend"
    else:
        test_scores, lr_test_abst = lr_scores(utt_emb[test_idx])
        conf = test_scores.max(axis=1)
        test_scores[(lr_test_abst > conf) | (conf < best_lr["tau"])] = 0.0
        test_m = evaluate(test_scores, truth_idx[test_idx], is_inherit[test_idx], 1e-6)
        method = "logreg"
        k, alpha, tau = best_blend["k"], best_blend["alpha"], best_lr["tau"]
    print(f"shipped method={method}  test: {test_m}")

    # gap-concept slice: top-1 on the test rows of previously uncovered concepts
    gap_m = None
    if gap_concept_ids:
        gap_idx_set = {cindex[c] for c in gap_concept_ids}
        gap_mask = np.array([int(t) in gap_idx_set for t in truth_idx[test_idx]])
        if gap_mask.any():
            best_t = test_scores[gap_mask].argmax(axis=1)
            gap_m = {
                "rows": int(gap_mask.sum()),
                "top1": float((best_t == truth_idx[test_idx][gap_mask]).mean()),
            }
            print(f"gap-concept test slice: {gap_m}")

    # --- artifacts ----------------------------------------------------------------
    out = DEFAULT_MODEL_DIR
    out.mkdir(parents=True, exist_ok=True)
    np.save(out / "anchor_embeddings.npy", anchor_emb)
    np.savez(out / "train_bank.npz", emb=bank_emb, concept_matrix=bank_concepts)
    np.savez(out / "logreg_resolver.npz",
             coef=logreg.coef_.astype(np.float32),
             intercept=logreg.intercept_.astype(np.float32),
             classes=logreg.classes_.astype(np.int64))
    (out / "concepts_meta.json").write_text(
        json.dumps({"concept_ids": concept_ids, "concept_names": concept_names}, ensure_ascii=False),
        encoding="utf-8",
    )
    (out / "config.json").write_text(
        json.dumps({"method": method, "alpha": alpha, "k": int(k), "tau": tau,
                    "n_concepts": len(concept_ids),
                    "limitation": "logreg cannot resolve the 10 store concepts unseen in "
                                  "training data; blend artifacts are kept for fallback/reasons"},
                   indent=2),
        encoding="utf-8",
    )

    lines = [
        "# Concept Resolver — Evaluation Report",
        "",
        f"Dataset: `{DATASET.name}` · concepts in store: {len(concept_ids)} · "
        f"bank: {len(bank_rows)} explicit train rows ({int((seen > 0).sum())} concepts seen)",
        f"Frozen splits: train {len(train)} / val {len(val)} / test {len(test)} (shared with Part 1)",
        f"Shipped: **{method}** (alpha={alpha}, k={k}, tau={tau})",
        "",
        "| candidate | val combined | test top1(rank) | test top3(rank) | test top1(final) | abstain P | abstain R | abstain F1 |",
        "|---|---|---|---|---|---|---|---|",
        f"| blend{' **(shipped)**' if ship_blend else ''} | {best_blend['m']['combined']:.4f} | - | - | - | - | - | - |",
        f"| logreg{'' if ship_blend else ' **(shipped)**'} | {best_lr['m']['combined']:.4f} | - | - | - | - | - | - |",
        "",
        "## Shipped-method test metrics",
        "",
        f"- top-1 accuracy (ranking, explicit rows): **{test_m['top1_rank']:.4f}**",
        f"- top-3 accuracy (ranking, explicit rows): **{test_m['top3_rank']:.4f}**",
        f"- top-1 after abstain rule: **{test_m['top1_final']:.4f}**",
        f"- abstain on INHERIT rows: P {test_m['abstain_precision']:.4f} / R {test_m['abstain_recall']:.4f} / F1 **{test_m['abstain_f1']:.4f}**",
        f"- combined: **{test_m['combined']:.4f}**",
    ]
    if gap_m:
        lines.append(
            f"- previously uncovered concepts (Qwen-generated rows, {gap_m['rows']} test rows): "
            f"top-1 **{gap_m['top1']:.4f}**"
        )
    lines += [
        "",
        f"Build time: {time.time() - t0:.0f}s",
    ]
    (out / "eval_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"artifacts -> {out}")


if __name__ == "__main__":
    main()
